project:
  type: website

website:
  title: "Visual Analytics and Application"
  image: "Images/Logo.png"
  favicon: "Images/Icon.png"
  page-navigation: true
  navbar:
    logo: "Images/Logo.png"
    title: false
    collapse-below: lg
    search: true
    left: 
      - text: "{{< fa pencil size=lg >}} Hands-on Exercises"
        menu: 
          - text: 1. A Layered Grammar of Graphics - ggplot2 methods
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html
          - text: 2. Beyond ggplot2 Fundamentals
            href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html
          - text: 3. Programming Interactive Data Visualisation & Animated Statistical Graphics with R
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html
          - text: 4. Visualising Distribution, Statistical Analysism Uncertainty and Bulding Funnel Plot with R
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html
          - text: 5. Building Ternary Plot, Visual Correlation Analysis / Multivariate Analysis, and Treemap Visualisation
            href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html
          - text: 6. Visualising and Analysing Time-oriented Data
            href: Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html
          - text: 7. Choropleth Mapping, Geospatial Point Data, and Analytical Mapping
            href: Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html   
          - text: 8. Modelling, Visualising and Analysing Network Data with R
            href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html  
          - text: 9. Visualising and Analysing Text Data
            href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex09.html 
          - text: 10. Information Dashboard Design - R methods
            href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex10.html 
            
      - text: "{{< fa landmark size=lg >}} In-class Exercises"
        menu: 
          - text: In-Class Exercise 1
            href: In-class_Ex/In-class_Ex01/In-class_Ex01.html
          - text: In-Class Exercise 2
            href: In-class_Ex/In-class_Ex02/In-class_Ex02.html
          - text: In-Class Exercise 3
            href: In-class_Ex/In-class_Ex03/In-class_Ex03.html
          - text: In-Class Exercise 4
            href: In-class_Ex/In-class_Ex04/In-class_Ex04.html
          - text: In-Class Exercise 5
            href: In-class_Ex/In-class_Ex05/In-class_Ex05.html   
          - text: In-Class Exercise 6
            href: In-class_Ex/In-class_Ex05/In-class_Ex06.html  
          - text: In-Class Exercise 7
            href: In-class_Ex/In-class_Ex05/In-class_Ex07.html  
          - text: In-Class Exercise 8
            href: In-class_Ex/In-class_Ex05/In-class_Ex08.html  
 
      - text: "{{< fa book-bookmark size=lg >}} Take-home Exercises"
        menu: 
          - text: Take-home Exercise 1
            href: Take-Home_Ex/Take-Home_Ex1/Take-Home_Ex1.html    
          - text: Take-home Exercise 2
            href: Take-Home_Ex/Take-Home_Ex2/Take-Home_Ex2.html  
          - text: Take-home Exercise 3
            href: Take-Home_Ex/Take-Home_Ex3/Take-Home_Ex3.html  
          - text: Take-home Exercise 4
            href: Take-Home_Ex/Take-Home_Ex4/Take-Home_Ex4.html              
      - text: "{{< fa user-group size=lg >}} Projects"
        menu: 
          - text: Coming soon!
            href: "" 
    right:
      - href: index.qmd
        text: "{{< fa house size=lg >}}"
      - href: about.qmd
        text: "{{< fa paw size=lg >}}"
  
  page-footer: 
    right: "Blog made with 💜 and [Quarto](https://quarto.org/)"
    border: "#65666a"

      

format:
  html:
    grid:
      margin-width: 250px
    toc: true
    toc_float: true
    theme: 
      - theme.scss
    highlight-style: tango
    code-copy: hover
    code-overflow: wrap
    css: styles.css

editor: visual
