{
  "hash": "7a5f75d126c0084a4afabc61afc5c926",
  "result": {
    "markdown": "---\ntitle: \"Take-home Exercise 1: Investigating Student Performance with Data Visualisations\"\ndate: \"21 Jan 2024\"\ndate-modified: \"last-modified\"\neditor: visual\ntoc-depth: 4\nexecute:\n  freeze: true #never re-render during project render\n  echo: true #if false, displays charts without codes\n  eval: true #if false, displays codes without charts\n  warning: false #dont display if there are any warnings\nformat: \n  html:\n    code-fold: false\n    code-overflow: scroll\n    code-summary: \"Show the code\"\n    code-line-numbers: false\n---\n\n\n![](images/placeholder.PNG){fig-align=\"center\"}\n\n# 1 Overview\n\n## 1.1 Background\n\nThe OECD Programme for International Student Assessment (PISA) surveys collected data on 15 year-old students' performances in reading, mathematics and science, as well as contextual information on students' background, home characteristics and school factors which could influence performance. It provides the most comprehensive and rigorous international assessment of student learning outcomes. Results from PISA indicate the quality and equity of learning outcomes attained around the world, and allow educators and policy makers to learn from the policies and practices applied in other countries.\n\nThis could be used to create shared points of reference and spur collaboration to act on the data. The goal of PISA was to help schools and policy makers shift from looking inward at each other within the same education system to looking outward: to teachers, schools and policy makers across the world.\n\nThe latest PISA assessment took place in 2022 and consisted of 8 questionnaires completed by different education systems stakeholders (students, teachers, parents, and school principals).\n\n## 1.2 The Data\n\nThe data for this exercise is the **Student questionnaire data file** in SAS format, retrieved from [OECD's PISA 2022 Database](https://www.oecd.org/pisa/data/2022database/).\n\n![](images/PISA.PNG){fig-align=\"center\" width=\"450\"}\n\nSupplementary materials used in conjunction with dataset:\n\n-   [Codebook](https://webfs.oecd.org/pisa2022/CY08MSP_CODEBOOK_5thDecember23.xlsx)\n-   [Master Questionnaire](https://www.oecd.org/pisa/data/2022database/CY8_202111_QST_MS_STQ_CBA_NoNotes.pdf)\n-   [Technical Report](https://www.oecd.org/pisa/data/pisa2022technicalreport/)\n\n## 1.3 The Task\n\nUsing the **2022 Student Questionnaire Dataset**, this post aims to use appropriate Exploratory Data Analysis (EDA) methods and ggplot2 functions to uncover:\n\n-   the distribution of [Singapore students']{.underline} performance in **mathematics, reading, and science**, and\n-   the relationship between these performances with **schools, gender and socioeconomic status** of the students.\n\n# 2 Loading Packages\n\n+----------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| **Library**                                                                                  | **Description**                                                                                                                                                                                                                                             |\n+==============================================================================================+=============================================================================================================================================================================================================================================================+\n| [**tidyverse**](https://www.tidyverse.org/)                                                  | A collection of core packages designed for data science, used extensively for data preparation and wrangling.                                                                                                                                               |\n+----------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| [**haven**](https://haven.tidyverse.org/)                                                    | To enable R to read and write various data formats such as SAS and SPSS.                                                                                                                                                                                    |\n+----------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| [**knitr**](https://yihui.org/knitr/)                                                        | For dynamic report generation.                                                                                                                                                                                                                              |\n+----------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| [**patchwork**](https://patchwork.data-imaginist.com/)                                       | For preparing composite figure created using ggplot2.                                                                                                                                                                                                       |\n+----------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| [**ggthemes**](https://yutannihilation.github.io/allYourFigureAreBelongToUs/ggthemes/)       | Extra themes, geoms, and scales for ggplot2.                                                                                                                                                                                                                |\n+----------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| [**scales**](https://scales.r-lib.org/)                                                      | For data labels and annotations for ggplot2                                                                                                                                                                                                                 |\n+----------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| [**ggridges**](https://cran.r-project.org/web/packages/ggridges/vignettes/introduction.html) | For ridgeline plots that create the impression of a mountain range. They can be useful for visualising changes in distributions over time or space.                                                                                                         |\n+----------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| [**ggpubr**](https://github.com/kassambara/ggpubr)                                           | For publication-ready plots.                                                                                                                                                                                                                                |\n+----------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| [**gganimate**](https://gganimate.com/)                                                      | Extends the grammat of graphics as implemented by ggplot2 to include the description of animation.                                                                                                                                                          |\n+----------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| [**ggdist**](https://mjskay.github.io/ggdist/)                                               | For visualisations of distributions and uncertainty.                                                                                                                                                                                                        |\n+----------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| [**ggtext**](https://wilkelab.org/ggtext/)                                                   | Supports improved text rendering for ggplot2.                                                                                                                                                                                                               |\n+----------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| [**ggalt**](https://yonicd.github.io/ggalt/index.html)                                       | A compendium of 'geoms', 'coords', 'stats', scales and fonts for ggplots2.                                                                                                                                                                                  |\n+----------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| [**ggextra**](https://github.com/daattali/ggExtra)                                           | For adding marginal plots to ggplot2.                                                                                                                                                                                                                       |\n+----------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| [**cowplot**](https://github.com/wilkelab/cowplot)                                           | Provides vrious features that help with creating publication-quality figures such as a set of themes, functions to align plots and arrange them into complex compound figures, and functions that make it easy to annotate plots and mix plots with images. |\n+----------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| [**ggnewscale**](https://eliocamp.github.io/ggnewscale/)                                     | For defining scales in ggplot2.                                                                                                                                                                                                                             |\n+----------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n\n: {tbl-colwidths=\"\\[20,80\\]\"}\n\nThe following code chunk uses `p_load()` of [**pacman**](https://rpubs.com/akshaypatankar/594834) package to check if tidyverse packages are installed in the computer. If they are, the libraries will be called into R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, haven, knitr,\n               patchwork, ggthemes, scales,\n               ggridges, ggpubr, gganimate,\n               ggdist, ggtext, ggalt,\n               cowplot, ggnewscale)\n```\n:::\n\n\n# 3 PISA Data\n\nIn the next two sections, I'll go through all of the steps I took to wrangle the data -- from reading in the raw data to my final dataset. I'll be using the **tidyverse** package, specifically **dplyr** for data manipulation and **haven** for reading in data.\n\n::: panel-tabset\n## Importing sas file\n\nThe code chunk below imports the *2022 Student Questionnaire* dataset downloaded from OECD's PISA 2022 Database using the [`read_sas()`](https://haven.tidyverse.org/reference/read_sas.html) function of the [**haven**](https://haven.tidyverse.org/) package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstu <- read_sas(data_file = \"data/cy08msp_stu_qqq.sas7bdat\")\n```\n:::\n\n\nThe dataset is in a tibble dataframe, containing 613,744 observations (rows) across 1,279 variables (columns). Each observation corresponds to an entry from a student who participated in the 2022 PISA survey for students, and the variables correspond to information from students on various aspects of their home, family, and school background.\n\nNote that the first variable *CNT* refers to the country of response, we can use this to filter for Singapore (where *CNT = SGP*) responses for our analysis. [`filter()`](https://dplyr.tidyverse.org/reference/filter.html) of the [**dplyr**](https://dplyr.tidyverse.org/) package allows us to perform this extraction of participating country.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstu_SG <- stu %>%\n  filter(CNT == \"SGP\")\n```\n:::\n\n\nThe resulting data contains 6,606 rows/observations across 1,279 columns/variables.\n\nThe *.rds* file format is usually smaller than its SAS file counterpart and will therefore take up less storage space. The *.rds* file will also preserve data types and classes such as factors and dates eliminating the need to redefine data types after loading the file. For fast and space efficient data storage, files can be exported as RDS and re-imported into R using [`write_rds()`](https://readr.tidyverse.org/reference/read_rds.html) and [`read_rds()`](https://readr.tidyverse.org/reference/read_rds.html) respectively.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(stu_SG, \"data/stu_SG.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstu_SG <- read_rds(\"data/stu_SG.rds\")\n```\n:::\n\n\n## Duplicates Check\n\nBefore moving on to the next step, let us check for duplicated records to prevent double counting of our results with the help of `group_by_all()` to detect if there are more than one instance of a row with the same details throughout all the columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nduplicate <- stu_SG %>% \n  group_by_all() %>% \n  filter(n()>1) %>% \n  ungroup()\n  \nduplicate\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 0 × 1,279\n# ℹ 1,279 variables: CNT <chr>, CNTRYID <dbl>, CNTSCHID <dbl>, CNTSTUID <dbl>,\n#   CYC <chr>, NatCen <chr>, STRATUM <chr>, SUBNATIO <chr>, REGION <dbl>,\n#   OECD <dbl>, ADMINMODE <dbl>, LANGTEST_QQQ <dbl>, LANGTEST_COG <dbl>,\n#   LANGTEST_PAQ <dbl>, Option_CT <dbl>, Option_FL <dbl>, Option_ICTQ <dbl>,\n#   Option_WBQ <dbl>, Option_PQ <dbl>, Option_TQ <dbl>, Option_UH <dbl>,\n#   BOOKID <dbl>, ST001D01T <dbl>, ST003D02T <dbl>, ST003D03T <dbl>,\n#   ST004D01T <dbl>, ST250Q01JA <dbl>, ST250Q02JA <dbl>, ST250Q03JA <dbl>, …\n```\n:::\n:::\n\n\nResults confirm that there are no duplicated records found.\n\nI also wanted to check if every observation in the dataset belongs to a unique Student using *CNTSTUID*, which is the Intl. Student ID.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_distinct(stu_SG$CNTSTUID)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6606\n```\n:::\n:::\n\n\nThe results confirm that each observation pertains to a unique Student as there are 6606 distinct student IDs for the 6606 rows in the dataset.\n:::\n\n# 4 Data Wrangling\n\nThe following flowchart shows the main variables used and created in this study.\n\n\n```{mermaid}\n%%| fig-width: 8\n%%| echo: false\nflowchart LR\n    A(Student PISA Survey) -->|\\nFilter| B[Singapore Students' Responses]\n\n    B--> F[Schools]\n    F-.-> F1([CNTSCHID])\n    \n    B--> B1[Student ID]\n    B1-.-> B1.1([CNTSTUID])  \n\n    B--> G[Gender]\n    G-.-> M([ST004D01T]) \n\n    B--> H[Socioeconomic status]\n    H--> H1[Immigration status] \n    H1-.-> H1A([IMMIG])        \n    H--> H2[Parental occupational status] \n    H2-.-> H2A([OCOD1, OCOD2])\n    H--> H3[Educational resources]\n    H3-.-> H3A([ST250Q02JA, ST250Q03JA, ST250Q05JA])\n\n    H--> H6[Parental educational status]\n    H6-.-> H6A([MISCED, FISCED])         \n\n    B--> C[Math performance]\n    C--> C1[Out-of-school study time]\n    C1-.-> C1A([ST296Q01JA])\n    C--> C3[Plausible Values]   \n    C3-.-> C3A([PV1MATH to PV10MATH])        \n\n    B--> D[Reading performance]\n    D--> D1[Out-of-school study time]\n    D1-.-> D1A([ST296Q02JA]) \n    D--> D2[Plausible Values]\n    D2-.-> D2A([PV1READ to PV10READ])     \n\n    B--> E[Science performance]\n    E--> E1[Out-of-school study time]\n    E1-.-> E1A([ST296Q03JA])   \n    E--> E2[Plausible Values]\n    E2-.-> E12([PV1SCIE to PV10SCIE])\n\n    1(Schools PISA Survey) -->|\\nFilter| 1.1[Singapore Schools \\nResponses]\n    F1--> F2[Type, Student-Teacher ratio]\n    F2-.-> F2a([SCHLTYPE, STRATIO])\n    1.1-.->F1\n```\n\n\n## 4.1 Variable Selection\n\nNow, I want to just keep the columns that are useful to me. Both [**Technical Report**](https://www.oecd.org/pisa/data/pisa2022technicalreport/) and [**Codebook**](https://webfs.oecd.org/pisa2022/CY08MSP_CODEBOOK_5thDecember23.xlsx) on PISA's website were particularly helpful in deciphering the various variable names.\n\nIn particular, [Chapter 19: Scaling procedures and construct validation of context questionnaire data](https://www.oecd.org/pisa/data/pisa2022technicalreport/PISA-2022-Technical-Report-Ch-19-PISA-Scaling-Procedures-Construct-Validation-Context-Questionnaire-Data.pdf) of the Technical Report provides detailed descriptions of the derived variables in each questionnaire while the [Codebook](https://webfs.oecd.org/pisa2022/CY08MSP_CODEBOOK_5thDecember23.xlsx) provides information on variable names, variable locations, format information, variable labels, questionnaire text, values, and frequencies.\n\nBelow are the list of variables retained for this study, which can be grouped into 4 broad categories of School, Gender, Socio-economic status, Performance (Math, Reading, and Science). Details are extracted from the Codebook:\n\n+----------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Category             | Variable Name       | Description/Question                                                                                                  | Type   | Encoding Scheme                                                                                                                                          |\n+======================+=====================+=======================================================================================================================+========+==========================================================================================================================================================+\n| School               | CNTSCHID            | Intl. School ID                                                                                                       | NUM    |                                                                                                                                                          |\n+----------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Gender               | ST004D01T           | Student (Standardized) Gender                                                                                         | NUM    | 1 - Female                                                                                                                                               |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 2 - Male                                                                                                                                                 |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | .N/97 - Not Applicable                                                                                                                                   |\n+----------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Socioeconomic Status | IMMIG               | Index on immigrant background (OECD definition)                                                                       | NUM    | 1 - Native Student                                                                                                                                       |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 2 - Second-Generation Student                                                                                                                            |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 3 - First Generation Student                                                                                                                             |\n+----------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Socioeconomic Status | OCOD1               | ISCO-08 Occupation code - Mother                                                                                      | CHAR   | There are multiple labels for various occupations. However, we can generally group the following groups as \"Unemployed\" and the remaining as \"Employed\": |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 9701 - Doing housework, bringing up children                                                                                                             |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 9702 - Learning, studying                                                                                                                                |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 9703 - Retired, pensioner, on unemployment benefits                                                                                                      |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 9704 - I do not know, it's hard to say                                                                                                                   |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 9997 - Not applicable                                                                                                                                    |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 9998 - Invalid                                                                                                                                           |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 9999 - No response                                                                                                                                       |\n+----------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Socioeconomic Status | OCOD2               | ISCO-08 Occupation code - Father                                                                                      | CHAR   | Same as previous variable.                                                                                                                               |\n+----------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Socioeconomic Status | ST250Q02JA          | Which of the following are in your \\[home\\]: A computer (laptop, desktop, or tablet) that you can use for school work | NUM    | 1 - Yes                                                                                                                                                  |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 2 - No                                                                                                                                                   |\n+----------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Socioeconomic Status | ST250Q03JA          | Which of the following are in your \\[home\\]: Educational Software or Apps                                             | NUM    | 1 - Yes                                                                                                                                                  |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 2 - No                                                                                                                                                   |\n+----------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Socioeconomic Status | ST250Q05JA          | Which of the following are in your \\[home\\]: Internet access (e.g. Wi-fi) (excluding through smartphones)             | NUM    | 1 - Yes                                                                                                                                                  |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 2 - No                                                                                                                                                   |\n+----------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Socioeconomic Status | MISCED              | Mother's level of education (ISCED)                                                                                   | NUM    | 1 - Less than ISCED Level 1                                                                                                                              |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 2 - ISCED level 1                                                                                                                                        |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 3 - ISCED level 2                                                                                                                                        |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 4 - ISCED level 3.3                                                                                                                                      |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 5 - ISCED level 3.4                                                                                                                                      |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 6 - ISCED level 4                                                                                                                                        |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 7 - ISCED level 5                                                                                                                                        |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 8 - ISCED level 6                                                                                                                                        |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 9 - ISCED level 7                                                                                                                                        |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 10 - ISCED level 8                                                                                                                                       |\n+----------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Socioeconomic Status | FISCED              | Father's level of education (ISCED)                                                                                   | NUM    | Same as previous variable.                                                                                                                               |\n+----------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Math                 | ST296Q01JA          | How much time spent on homework in: Mathematics homework                                                              | NUM    | 1 - Up to 30 minutes a day                                                                                                                               |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 2 - More than 30 minutes and up to 1 hour a day                                                                                                          |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 3 - More than 1 hour and up to 2 hours a day                                                                                                             |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 4 - More than 2 hours and up to 3 hours a day                                                                                                            |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 5 - More than 3 hours and up to 4 hours a day                                                                                                            |\n|                      |                     |                                                                                                                       |        |                                                                                                                                                          |\n|                      |                     |                                                                                                                       |        | 6 - More than 4 hours a day                                                                                                                              |\n+----------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Reading              | ST296Q02JA          | How much time spent on homework in: \\[Test language\\] homework                                                        | NUM    | Same as previous variable.                                                                                                                               |\n+----------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Science              | ST296Q03JA          | How much time spent on homework in: \\[Science\\] homework                                                              | NUM    | Same as previous variable.                                                                                                                               |\n+----------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Math                 | PV1MATH to PV10MATH | Plausible Values 1 to 10 in Mathematics                                                                               | NUM    |                                                                                                                                                          |\n+----------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Reading              | PV1READ to PV10READ | Plausible Value 1 to 10 in Science                                                                                    | NUM    |                                                                                                                                                          |\n+----------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Science              | PV1SCIE to PV10SCIE | Plausible Values 1 to 10 in Science                                                                                   | NUM    |                                                                                                                                                          |\n+----------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------+\n\n: {tbl-colwidths=\"\\[10,10,30,5,45\\]\" .striped .hover}\n\nThe code chunk below filters for the selected variables based on their column names using `select()` and renames them to more intuitive headers using `rename()` from the **dplyr** package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstu_SG_filtered <- stu_SG %>%\n\n  # Retains desired variables for further analysis  \n  select(CNTSCHID,ST004D01T,IMMIG,OCOD1,OCOD2, ST250Q02JA, ST250Q03JA, ST250Q05JA, MISCED, FISCED, ST296Q01JA,ST296Q02JA, ST296Q03JA, PV1MATH, PV2MATH, PV3MATH, PV4MATH, PV5MATH, PV6MATH, PV7MATH, PV8MATH, PV9MATH, PV10MATH, PV1READ, PV2READ, PV3READ, PV4READ, PV5READ, PV6READ, PV7READ, PV8READ, PV9READ, PV10READ, PV1SCIE, PV2SCIE, PV3SCIE, PV4SCIE, PV5SCIE, PV6SCIE, PV7SCIE, PV8SCIE ,PV9SCIE ,PV10SCIE) %>% \n  \n  # Renames columns to more intuitive headers\n  dplyr::rename(SchID=\"CNTSCHID\",\n           Gender=\"ST004D01T\",\n           Immigration_Status=\"IMMIG\",\n           Occupation_Status_Father=\"OCOD1\",\n           Occupation_Status_Mother=\"OCOD2\", \n           Have_Comp=\"ST250Q02JA\", \n           Have_EduSW=\"ST250Q03JA\", \n           Have_Internet=\"ST250Q05JA\", \n           Edu_Mother=\"MISCED\", \n           Edu_Father=\"FISCED\", \n           Time_HW_Math=\"ST296Q01JA\",\n           Time_HW_Reading=\"ST296Q02JA\", \n           Time_HW_Science=\"ST296Q03JA\"\n           )\n```\n:::\n\n\n## 4.2 Handling missing values\n\nNow, I need to remove incomplete rows that have missing data in them. The main reason for doing this is that later on, I want to recode the variables into more intuitive descriptions. If there are NA's in the columns, that might affect the recoding if a value is accidentally inputted to a variable which was originally NA.\n\n`is.na()` allows us to identify missing values in our dataset and `sum()` counts the frequency of such missing values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Checks for NA in each column\nsum(is.na(stu_SG_filtered$SchID))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(stu_SG_filtered$Gender))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(stu_SG_filtered$Immigration_Status))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 236\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(stu_SG_filtered$Occupation_Status_Father))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(stu_SG_filtered$Occupation_Status_Mother))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(stu_SG_filtered$Have_Comp))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 45\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(stu_SG_filtered$Have_EduSW))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 60\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(stu_SG_filtered$Have_Internet))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 46\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(stu_SG_filtered$Edu_Father))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 97\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(stu_SG_filtered$Edu_Mother))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 74\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(stu_SG_filtered$Time_HW_Reading))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 77\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(stu_SG_filtered$Time_HW_Math))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 70\n```\n:::\n\n```{.r .cell-code}\nsum(is.na(stu_SG_filtered$Time_HW_Science))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 87\n```\n:::\n:::\n\n\nThe variables with missing values are: *Immigration_Status*, *Have_Comp*, *Have_EduSW*, *Have_Internet*, *Edu_Father*, *Edu_Mother*, *Time_HW_Reading*, *Time_HW_Math*, and *Time_HW_Science*.\n\n`drop_na()` drops rows where any column specified contains a missing value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstu_SG_filtered <- drop_na(stu_SG_filtered,\n                           # Drops rows where either of these columns have NAs\n                           Immigration_Status, Have_Comp, Have_EduSW, Have_Internet, Edu_Father,\n                           Edu_Mother, Time_HW_Reading, Time_HW_Math, Time_HW_Science)\n\n# Here's what the dataset looks like so far\nstu_SG_filtered\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6,232 × 43\n      SchID Gender Immigration_Status Occupation_Status_Father\n      <dbl>  <dbl>              <dbl> <chr>                   \n 1 70200052      1                  1 9701                    \n 2 70200134      2                  1 31                      \n 3 70200112      2                  1 9701                    \n 4 70200004      2                  1 41                      \n 5 70200152      1                  1 23                      \n 6 70200043      1                  3 9701                    \n 7 70200049      2                  1 11                      \n 8 70200107      2                  3 23                      \n 9 70200012      1                  1 1                       \n10 70200061      2                  1 34                      \n# ℹ 6,222 more rows\n# ℹ 39 more variables: Occupation_Status_Mother <chr>, Have_Comp <dbl>,\n#   Have_EduSW <dbl>, Have_Internet <dbl>, Edu_Mother <dbl>, Edu_Father <dbl>,\n#   Time_HW_Math <dbl>, Time_HW_Reading <dbl>, Time_HW_Science <dbl>,\n#   PV1MATH <dbl>, PV2MATH <dbl>, PV3MATH <dbl>, PV4MATH <dbl>, PV5MATH <dbl>,\n#   PV6MATH <dbl>, PV7MATH <dbl>, PV8MATH <dbl>, PV9MATH <dbl>, PV10MATH <dbl>,\n#   PV1READ <dbl>, PV2READ <dbl>, PV3READ <dbl>, PV4READ <dbl>, …\n```\n:::\n:::\n\n\nThe output shows that 6,232 observations are retained.\n\n## 4.3 Recoding Categorical Variables\n\n::: panel-tabset\n## Gender\n\n`recode()` helps to set new values by providing a mapping from old to new values. Here, Gender = 1 is mapped to Female and Gender = 2 is mapped to Male. The recoded variable is then assigned using `mutate()` of the **dplyr** package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstu_SG_filtered <- stu_SG_filtered %>%\n  mutate(Gender=(recode(Gender, '1'=\"Female\", \n                        '2'=\"Male\")))\n```\n:::\n\n\n## Immigration Status\n\nThe code chunk below uses `mutate()` to replace the existing variable which sets its value based on the `recode()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstu_SG_filtered <- stu_SG_filtered %>%\n  mutate(Immigration_Status=\n           (recode(Immigration_Status, \n                   '1'=\"Native\", \n                   '2'=\"Second-Gen\", \n                   '3'=\"Third-Gen\")))\n```\n:::\n\n\n## Occupation Status\n\nThere are multiple labels for various occupations. However, we can generally group the following groups as \"Unemployed\" and the remaining as \"Employed\":\n\n-   9701 - Doing housework, bringing up children\n-   9702 - Learning, studying\n-   9703 - Retired, pensioner, on unemployment benefits\n-   9704 - I do not know, it's hard to say\n-   9997 - Not applicable\n-   9998 - Invalid\n-   9999 - No response\n\nThe code chunk below makes use of the [`ifelse()`](https://rdrr.io/r/base/ifelse.html) function to evaluate if the Occupation code falls in the list above with the help of the `%in%` operator. If it is, output will be \"Unemployed\", else it would be shown as \"Employed\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Occupation_Status_Father\nstu_SG_filtered <- stu_SG_filtered %>% \n  mutate(Occupation_Status_Father = ifelse(Occupation_Status_Father %in% c(\"9701\", \"9702\", \"9703\", \"9704\", \"9997\", \"9998\", \"9999\"), \n                                           \"Unemployed\", \n                                           \"Employed\"))\n\n# Occupation_Status_Mother\nstu_SG_filtered <- stu_SG_filtered %>% \n  mutate(Occupation_Status_Mother = ifelse(Occupation_Status_Mother %in% c(\"9701\", \"9702\", \"9703\", \"9704\", \"9997\", \"9998\", \"9999\"), \n                                           \"Unemployed\", \n                                           \"Employed\"))  \n```\n:::\n\n\n## Access to Computer, Educational Software, and Internet at Home\n\nFor access to computer, educational software, and internet columns, `ifelse()` statement returns a \"Yes\" when the number is 1, else it returns a \"No\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Have_Comp\nstu_SG_filtered <- stu_SG_filtered %>% \n  mutate(Have_Comp = ifelse(Have_Comp==\"1\", \n                            \"Yes\", \n                            \"No\"))\n\n# Have_EduSW\nstu_SG_filtered <- stu_SG_filtered %>% \n  mutate(Have_EduSW = ifelse(Have_EduSW==\"1\", \n                            \"Yes\", \n                            \"No\"))\n\n# Have_Internet\nstu_SG_filtered <- stu_SG_filtered %>% \n  mutate(Have_Internet = ifelse(Have_Internet==\"1\", \n                            \"Yes\", \n                            \"No\"))\n```\n:::\n\n\n## Parental Educational Status\n\nPISA Survey adopts the International Standard Classification of Education (ISCED), which is the official framework used to facilitate international comparisons of education systems.\n\nDiagram below shows Singapore qualifications mapped against ISCED levels obtained from [UNESCO](https://isced.uis.unesco.org/wp-content/uploads/sites/15/uis_isced_uploads/6841c457f6d3a64dcc01efb65e886330.jpg).\n\n![](images/ISCED.PNG){fig-align=\"center\"}\n\nThe following mapping is used to recode for further data analysis:\n\n+--------------+-------------------------+-----------------------------+----------------+\n| PISA Value   | PISA Value Description  | Converted Education Level   | Recoded Group  |\n+==============+=========================+=============================+================+\n| 1            | Less than ISCED Level 1 | Early childhood             | Pre-Primary    |\n+--------------+-------------------------+-----------------------------+----------------+\n| 2            | ISCED level 1           | Primary                     | Primary        |\n+--------------+-------------------------+-----------------------------+----------------+\n| 3            | ISCED level 2           | Lower Secondary             | Secondary      |\n+--------------+-------------------------+-----------------------------+----------------+\n| 4            | ISCED level 3.3         | Upper Secondary             | Secondary      |\n+--------------+-------------------------+-----------------------------+----------------+\n| 6            | ISCED level 4           | Post-secondary Non-tertiary | Post-secondary |\n+--------------+-------------------------+-----------------------------+----------------+\n| 7            | ISCED level 5           | Diploma                     | Post-secondary |\n+--------------+-------------------------+-----------------------------+----------------+\n| 8            | ISCED level 6           | Bachelors                   | Tertiary       |\n+--------------+-------------------------+-----------------------------+----------------+\n| 9            | ISCED level 7           | Masters                     | Tertiary       |\n+--------------+-------------------------+-----------------------------+----------------+\n| 10           | ISCED level 8           | Doctoral                    | Tertiary       |\n+--------------+-------------------------+-----------------------------+----------------+\n\nAfter recoding, the `ordered()` function helps create such ordered factors to reflect the ascending sequence of the educational level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Edu_Mother\nstu_SG_filtered <- stu_SG_filtered %>%\n  mutate(Edu_Mother=(recode(Edu_Mother,         \n                                    '1'=\"Pre-Primary\",   \n                                    '2'=\"Primary\", \n                                    '3'=\"Secondary\",\n                                    '4'='Secondary',\n                                    '6'=\"Post-Secondary\",\n                                    '7'=\"Post-Secondary\",\n                                    '8'=\"Tertiary\",\n                                    '9'=\"Tertiary\",\n                                    '10'=\"Tertiary\")\n  )) \n\nstu_SG_filtered$Edu_Mother = ordered(stu_SG_filtered$Edu_Mother, \n                                             levels=c(\"Pre-Primary\", \"Primary\", \"Secondary\", \"Post-Secondary\", \"Tertiary\"))\n\n\n# Edu_Father\nstu_SG_filtered <- stu_SG_filtered %>%\n  mutate(Edu_Father=(recode(Edu_Father,         \n                                    '1'=\"Pre-Primary\",   \n                                    '2'=\"Primary\", \n                                    '3'=\"Secondary\",\n                                    '4'='Secondary',\n                                    '6'=\"Post-Secondary\",\n                                    '7'=\"Post-Secondary\",\n                                    '8'=\"Tertiary\",\n                                    '9'=\"Tertiary\",\n                                    '10'=\"Tertiary\")\n  )) \n\nstu_SG_filtered$Edu_Father = ordered(stu_SG_filtered$Edu_Father, \n                                             levels=c(\"Pre-Primary\", \"Primary\", \"Secondary\", \"Post-Secondary\", \"Tertiary\"))\n```\n:::\n\n\n## Time Spent on Homework\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\np_hwt_reading <- ggplot(data = stu_SG_filtered, \n       aes(x = Time_HW_Reading)) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 2600) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \\n\", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.2,\n      size=3) +  \n    labs(x = \"\",\n         y = \"\",\n         title=\"Reading\") + \n    theme(\n      panel.grid.major = element_blank(), \n      plot.title = element_text(size=9, face=\"bold\"),\n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),\n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    ) \n\np_hwt_math <- ggplot(data = stu_SG_filtered, \n       aes(x = Time_HW_Math)) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 2600) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \\n\", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.2,\n      size=3) +  \n    labs(x = \"\",\n         y = \"\",\n         title=\"Math\") + \n    theme(\n      panel.grid.major = element_blank(), \n      plot.title = element_text(size=9, face=\"bold\"),\n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),\n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    ) \n\np_hwt_sci <- ggplot(data = stu_SG_filtered, \n       aes(x = Time_HW_Science)) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 2600) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \\n\", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.2,\n      size=3) +  \n    labs(x = \"\",\n         y = \"\",\n         title=\"Science\") + \n    theme(\n      panel.grid.major = element_blank(), \n      plot.title = element_text(size=9, face=\"bold\"),\n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),\n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    ) \n\n\np_hwt_reading + p_hwt_sci + p_hwt_math +\n  plot_layout(widths=c(1,1,1)) +\n  plot_annotation(title=\"Time Spent on Homework in mins (before grouping)\", \n                  theme=theme(plot.title = element_text(hjust = 0),\n                  plot.background = element_rect(fill=\"#f5f5f5\", colour = \"#f5f5f5\"),\n                  panel.border = element_blank()))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nThe bar charts display the distribution of responses regarding the time spent on homework for the 3 subjects. We can see that the frequency dips significantly where response is 4 and above, i.e. after 2 hours. We can combine codes 4 through 6 to be analysed together.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Time_HW_Math\nstu_SG_filtered <- stu_SG_filtered %>%\n  mutate(Time_HW_Math=(recode(Time_HW_Math,         \n                                    '1'=\"<31\",   \n                                    '2'=\"31-60\", \n                                    '3'=\"61-120\",\n                                    '4'='>120',\n                                    '5'='>120',\n                                    '6'=\">120\")\n  )) \n\nstu_SG_filtered$Time_HW_Math = ordered(stu_SG_filtered$Time_HW_Math, \n                                             levels=c(\"<31\", \"31-60\", \"61-120\", \">120\"))\n# Time_HW_Reading\nstu_SG_filtered <- stu_SG_filtered %>%\n  mutate(Time_HW_Reading=(recode(Time_HW_Reading,         \n                                    '1'=\"<31\",   \n                                    '2'=\"31-60\", \n                                    '3'=\"61-120\",\n                                    '4'='>120',\n                                    '5'='>120',\n                                    '6'=\">120\")\n  )) \n\nstu_SG_filtered$Time_HW_Reading = ordered(stu_SG_filtered$Time_HW_Reading, \n                                             levels=c(\"<31\", \"31-60\", \"61-120\", \">120\"))\n\n# Time_HW_Science\nstu_SG_filtered <- stu_SG_filtered %>%\n  mutate(Time_HW_Science=(recode(Time_HW_Science,         \n                                    '1'=\"<31\",   \n                                    '2'=\"31-60\", \n                                    '3'=\"61-120\",\n                                    '4'='>120',\n                                    '5'='>120',\n                                    '6'=\">120\")\n  )) \n\nstu_SG_filtered$Time_HW_Science = ordered(stu_SG_filtered$Time_HW_Science, \n                                             levels=c(\"<31\", \"31-60\", \"61-120\", \">120\"))\n```\n:::\n\n\nThe distribution after combining and recoding looks like this:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\np2_hwt_reading <- ggplot(data = stu_SG_filtered, \n       aes(x = Time_HW_Reading)) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 2600) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \\n\", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.2,\n      size=3) +  \n    labs(x = \"\",\n         y = \"\",\n         title=\"Reading\") + \n    theme(\n      panel.grid.major = element_blank(), \n      plot.title = element_text(size=9, face=\"bold\"),\n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),\n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    ) \n\np2_hwt_math <- ggplot(data = stu_SG_filtered, \n       aes(x = Time_HW_Math)) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 2600) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \\n\", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.2,\n      size=3) +  \n    labs(x = \"\",\n         y = \"\",\n         title=\"Math\") + \n    theme(\n      panel.grid.major = element_blank(), \n      plot.title = element_text(size=9, face=\"bold\"),\n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),\n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    ) \n\np2_hwt_sci <- ggplot(data = stu_SG_filtered, \n       aes(x = Time_HW_Science)) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 2600) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \\n\", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.2,\n      size=3) +  \n    labs(x = \"\",\n         y = \"\",\n         title=\"Science\") + \n    theme(\n      panel.grid.major = element_blank(), \n      plot.title = element_text(size=9, face=\"bold\"),\n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),\n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    ) \n\n\np2_hwt_reading + p2_hwt_sci + p2_hwt_math +\n  plot_layout(widths=c(1,1,1)) +\n  plot_annotation(title=\"Time Spent on Homework in mins (after grouping)\", \n                  theme=theme(plot.title = element_text(hjust = 0),\n                  plot.background = element_rect(fill=\"#f5f5f5\", colour = \"#f5f5f5\"),\n                  panel.border = element_blank()))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n:::\n\n## 4.4 Data Type Conversion\n\n`glimpse()` of the **dplyr** package allows us to see all columns and their data type in the data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(stu_SG_filtered)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 6,232\nColumns: 43\n$ SchID                    <dbl> 70200052, 70200134, 70200112, 70200004, 70200…\n$ Gender                   <chr> \"Female\", \"Male\", \"Male\", \"Male\", \"Female\", \"…\n$ Immigration_Status       <chr> \"Native\", \"Native\", \"Native\", \"Native\", \"Nati…\n$ Occupation_Status_Father <chr> \"Unemployed\", \"Employed\", \"Unemployed\", \"Empl…\n$ Occupation_Status_Mother <chr> \"Employed\", \"Employed\", \"Unemployed\", \"Employ…\n$ Have_Comp                <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Ye…\n$ Have_EduSW               <chr> \"Yes\", \"Yes\", \"No\", \"Yes\", \"Yes\", \"Yes\", \"Yes…\n$ Have_Internet            <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Ye…\n$ Edu_Mother               <ord> Tertiary, Post-Secondary, Secondary, Post-Sec…\n$ Edu_Father               <ord> Post-Secondary, Post-Secondary, Secondary, Po…\n$ Time_HW_Math             <ord> <31, 61-120, 31-60, 61-120, >120, <31, <31, 3…\n$ Time_HW_Reading          <ord> <31, 31-60, 61-120, <31, 61-120, <31, <31, 31…\n$ Time_HW_Science          <ord> 31-60, 61-120, 61-120, 31-60, >120, <31, <31,…\n$ PV1MATH                  <dbl> 639.004, 697.191, 693.710, 427.317, 436.462, …\n$ PV2MATH                  <dbl> 601.251, 754.277, 654.450, 410.376, 453.450, …\n$ PV3MATH                  <dbl> 621.480, 671.940, 696.938, 423.586, 392.315, …\n$ PV4MATH                  <dbl> 631.596, 657.300, 646.187, 388.935, 439.986, …\n$ PV5MATH                  <dbl> 579.276, 621.126, 678.119, 330.962, 443.125, …\n$ PV6MATH                  <dbl> 591.791, 655.729, 644.019, 379.988, 452.648, …\n$ PV7MATH                  <dbl> 600.709, 747.934, 720.531, 398.535, 396.970, …\n$ PV8MATH                  <dbl> 587.322, 694.365, 671.425, 422.127, 459.945, …\n$ PV9MATH                  <dbl> 618.131, 742.732, 694.085, 375.354, 438.166, …\n$ PV10MATH                 <dbl> 581.973, 656.934, 668.304, 453.348, 448.084, …\n$ PV1READ                  <dbl> 676.298, 625.585, 620.116, 381.495, 448.199, …\n$ PV2READ                  <dbl> 692.247, 686.716, 559.078, 400.815, 560.636, …\n$ PV3READ                  <dbl> 690.981, 663.147, 554.767, 374.911, 365.478, …\n$ PV4READ                  <dbl> 643.067, 567.435, 587.026, 367.484, 469.970, …\n$ PV5READ                  <dbl> 627.908, 614.500, 591.806, 336.009, 503.664, …\n$ PV6READ                  <dbl> 684.676, 604.745, 570.547, 324.630, 481.215, …\n$ PV7READ                  <dbl> 661.380, 669.375, 599.078, 396.242, 436.800, …\n$ PV8READ                  <dbl> 674.070, 623.735, 545.610, 374.723, 531.226, …\n$ PV9READ                  <dbl> 666.282, 649.579, 610.466, 314.704, 480.997, …\n$ PV10READ                 <dbl> 657.387, 571.261, 590.758, 342.956, 478.578, …\n$ PV1SCIE                  <dbl> 710.634, 670.646, 666.095, 340.308, 456.333, …\n$ PV2SCIE                  <dbl> 618.739, 748.839, 604.771, 329.889, 453.400, …\n$ PV3SCIE                  <dbl> 591.623, 635.443, 704.217, 411.353, 498.937, …\n$ PV4SCIE                  <dbl> 659.770, 639.735, 687.659, 327.974, 532.324, …\n$ PV5SCIE                  <dbl> 635.892, 608.385, 690.974, 292.183, 508.231, …\n$ PV6SCIE                  <dbl> 646.901, 670.662, 617.175, 355.423, 504.461, …\n$ PV7SCIE                  <dbl> 603.569, 734.807, 692.886, 400.182, 404.572, …\n$ PV8SCIE                  <dbl> 621.352, 639.748, 630.900, 317.518, 549.457, …\n$ PV9SCIE                  <dbl> 659.674, 716.768, 656.620, 298.893, 411.062, …\n$ PV10SCIE                 <dbl> 649.719, 655.670, 649.087, 362.702, 473.613, …\n```\n:::\n:::\n\n\n::: {.brainbox .brain data-latex=\"brain\"}\n**Observations:**\n\n1.  *SchID* should be converted from `<dbl>` to `<chr>` format. It should be in categorical instead of numerical data type.\n\n2.  The columns *Gender*, *Immigration_Status*, *Occupation_Status_Father*, *Occupation_Status_Mother*, *Have_Comp*, *Have_EduSW*, *Have_Internet*, *Edu_Mother*, *Edu_Father*, *Time_HW_Math*, *Time_HW_Reading*, and *Time_HW_Science* are in numeric data type. These should be in factor data type for further processing.\n:::\n\nThe code chunk below does the following:\n\n1.  `across` of **dplyr** package is used to convert all character data type into factor for multiple columns. It applies `as.factor()` function to convert the variables from numeric to categorical data type each column specified in the *col* argument.\n2.  `as.character()` is used to convert the `SchID` variable from numeric to categorical data type.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncol <- c(\"Gender\", \"Immigration_Status\", \"Occupation_Status_Father\", \"Occupation_Status_Mother\",\n         \"Have_Comp\", \"Have_EduSW\", \"Have_Internet\", \"Edu_Mother\", \"Edu_Father\",\n         \"Time_HW_Math\", \"Time_HW_Reading\", \"Time_HW_Science\")\n\nstu_SG_filtered <- stu_SG_filtered %>%\n  mutate(across(col, as.factor)) %>%\n  mutate(SchID = as.character(SchID))\n```\n:::\n\n\nWe use `glimpse()` again to check the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(stu_SG_filtered)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 6,232\nColumns: 43\n$ SchID                    <chr> \"70200052\", \"70200134\", \"70200112\", \"70200004…\n$ Gender                   <fct> Female, Male, Male, Male, Female, Female, Mal…\n$ Immigration_Status       <fct> Native, Native, Native, Native, Native, Third…\n$ Occupation_Status_Father <fct> Unemployed, Employed, Unemployed, Employed, E…\n$ Occupation_Status_Mother <fct> Employed, Employed, Unemployed, Employed, Emp…\n$ Have_Comp                <fct> Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes, …\n$ Have_EduSW               <fct> Yes, Yes, No, Yes, Yes, Yes, Yes, Yes, Yes, Y…\n$ Have_Internet            <fct> Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes, …\n$ Edu_Mother               <ord> Tertiary, Post-Secondary, Secondary, Post-Sec…\n$ Edu_Father               <ord> Post-Secondary, Post-Secondary, Secondary, Po…\n$ Time_HW_Math             <ord> <31, 61-120, 31-60, 61-120, >120, <31, <31, 3…\n$ Time_HW_Reading          <ord> <31, 31-60, 61-120, <31, 61-120, <31, <31, 31…\n$ Time_HW_Science          <ord> 31-60, 61-120, 61-120, 31-60, >120, <31, <31,…\n$ PV1MATH                  <dbl> 639.004, 697.191, 693.710, 427.317, 436.462, …\n$ PV2MATH                  <dbl> 601.251, 754.277, 654.450, 410.376, 453.450, …\n$ PV3MATH                  <dbl> 621.480, 671.940, 696.938, 423.586, 392.315, …\n$ PV4MATH                  <dbl> 631.596, 657.300, 646.187, 388.935, 439.986, …\n$ PV5MATH                  <dbl> 579.276, 621.126, 678.119, 330.962, 443.125, …\n$ PV6MATH                  <dbl> 591.791, 655.729, 644.019, 379.988, 452.648, …\n$ PV7MATH                  <dbl> 600.709, 747.934, 720.531, 398.535, 396.970, …\n$ PV8MATH                  <dbl> 587.322, 694.365, 671.425, 422.127, 459.945, …\n$ PV9MATH                  <dbl> 618.131, 742.732, 694.085, 375.354, 438.166, …\n$ PV10MATH                 <dbl> 581.973, 656.934, 668.304, 453.348, 448.084, …\n$ PV1READ                  <dbl> 676.298, 625.585, 620.116, 381.495, 448.199, …\n$ PV2READ                  <dbl> 692.247, 686.716, 559.078, 400.815, 560.636, …\n$ PV3READ                  <dbl> 690.981, 663.147, 554.767, 374.911, 365.478, …\n$ PV4READ                  <dbl> 643.067, 567.435, 587.026, 367.484, 469.970, …\n$ PV5READ                  <dbl> 627.908, 614.500, 591.806, 336.009, 503.664, …\n$ PV6READ                  <dbl> 684.676, 604.745, 570.547, 324.630, 481.215, …\n$ PV7READ                  <dbl> 661.380, 669.375, 599.078, 396.242, 436.800, …\n$ PV8READ                  <dbl> 674.070, 623.735, 545.610, 374.723, 531.226, …\n$ PV9READ                  <dbl> 666.282, 649.579, 610.466, 314.704, 480.997, …\n$ PV10READ                 <dbl> 657.387, 571.261, 590.758, 342.956, 478.578, …\n$ PV1SCIE                  <dbl> 710.634, 670.646, 666.095, 340.308, 456.333, …\n$ PV2SCIE                  <dbl> 618.739, 748.839, 604.771, 329.889, 453.400, …\n$ PV3SCIE                  <dbl> 591.623, 635.443, 704.217, 411.353, 498.937, …\n$ PV4SCIE                  <dbl> 659.770, 639.735, 687.659, 327.974, 532.324, …\n$ PV5SCIE                  <dbl> 635.892, 608.385, 690.974, 292.183, 508.231, …\n$ PV6SCIE                  <dbl> 646.901, 670.662, 617.175, 355.423, 504.461, …\n$ PV7SCIE                  <dbl> 603.569, 734.807, 692.886, 400.182, 404.572, …\n$ PV8SCIE                  <dbl> 621.352, 639.748, 630.900, 317.518, 549.457, …\n$ PV9SCIE                  <dbl> 659.674, 716.768, 656.620, 298.893, 411.062, …\n$ PV10SCIE                 <dbl> 649.719, 655.670, 649.087, 362.702, 473.613, …\n```\n:::\n:::\n\n\n## 4.5 Variable Creation\n\n### 4.5.1 Calculating Average Plausible Values\n\nThe following code chunk calculates the mean Plausible Values of each row for each subject for the columns saved under *PV_Math*, *PV_Reading*, and *PV_Sci*.\n\n-   `c_across()` works with `rowwise()` to perform aggregations on a data frame a row at a time.\n    -   `c_across()` allows us to indicate the columns we want to transform.\n-   `na.rm=TRUE` ignores NA values when calculating the mean.\n-   `mutate()` creates new columns to store our new variable.\n-   `select()` and the `- minus sign` removes columns we no longer require.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Columns of interest\nPV_Math <- c(\"PV1MATH\", \"PV2MATH\", \"PV3MATH\", \"PV4MATH\", \"PV5MATH\", \"PV6MATH\", \"PV7MATH\", \"PV8MATH\", \"PV9MATH\", \"PV10MATH\")\nPV_Reading <- c(\"PV1READ\", \"PV2READ\", \"PV3READ\", \"PV4READ\", \"PV5READ\", \"PV6READ\", \"PV7READ\", \"PV8READ\", \"PV9READ\", \"PV10READ\")\nPV_Sci <- c(\"PV1SCIE\", \"PV2SCIE\", \"PV3SCIE\", \"PV4SCIE\", \"PV5SCIE\", \"PV6SCIE\", \"PV7SCIE\", \"PV8SCIE\", \"PV9SCIE\", \"PV10SCIE\")\n\n# Performing row-wise aggregation\nstu_SG_lean <- \n  stu_SG_filtered %>% \n  rowwise() %>% \n  mutate(Avg_Math = mean(c_across(PV_Math), na.rm=TRUE),\n         Avg_Reading = mean(c_across(PV_Reading), na.rm=TRUE),\n         Avg_Sci = mean(c_across(PV_Sci), na.rm=TRUE)) %>% \n  select(-c(PV_Math, PV_Reading, PV_Sci))\n```\n:::\n\n\n### 4.5.2 Retrieving Variables from Schools Questionnaire\n\nThe [**School Questionnaire**](https://www.oecd.org/pisa/data/2022database/) administered to school principals contains additional data we can use to further analyse how variations in school-related factors can affect students' performance.\n\nThe dataset in SAS format is retrieved from [OECD's PISA 2022 Database](https://www.oecd.org/pisa/data/2022database/).\n\n![](images/PISA.PNG){fig-align=\"center\" width=\"450\"}\n\n`read_sav` of the **haven** package lets us read SPSS data (in .sav data format) into RStudio.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsch <- read_sav(\"data/CY08MSP_SCH_QQQ.sav\")\n\nsch\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 21,629 × 432\n   CNT         CNTRYID CNTSCHID CYC   NatCen     STRATUM    SUBNATIO   REGION   \n   <chr+lbl>   <dbl+l>    <dbl> <chr> <chr+lbl>  <chr+lbl>  <chr+lbl>  <dbl+lbl>\n 1 ALB [Alban… 8 [Alb…   800001 08MS  000… [Alb… ALB… [ALB… 008… [Alb… 800 [Alb…\n 2 ALB [Alban… 8 [Alb…   800002 08MS  000… [Alb… ALB… [ALB… 008… [Alb… 800 [Alb…\n 3 ALB [Alban… 8 [Alb…   800003 08MS  000… [Alb… ALB… [ALB… 008… [Alb… 800 [Alb…\n 4 ALB [Alban… 8 [Alb…   800004 08MS  000… [Alb… ALB… [ALB… 008… [Alb… 800 [Alb…\n 5 ALB [Alban… 8 [Alb…   800005 08MS  000… [Alb… ALB… [ALB… 008… [Alb… 800 [Alb…\n 6 ALB [Alban… 8 [Alb…   800006 08MS  000… [Alb… ALB… [ALB… 008… [Alb… 800 [Alb…\n 7 ALB [Alban… 8 [Alb…   800007 08MS  000… [Alb… ALB… [ALB… 008… [Alb… 800 [Alb…\n 8 ALB [Alban… 8 [Alb…   800008 08MS  000… [Alb… ALB… [ALB… 008… [Alb… 800 [Alb…\n 9 ALB [Alban… 8 [Alb…   800009 08MS  000… [Alb… ALB… [ALB… 008… [Alb… 800 [Alb…\n10 ALB [Alban… 8 [Alb…   800010 08MS  000… [Alb… ALB… [ALB… 008… [Alb… 800 [Alb…\n# ℹ 21,619 more rows\n# ℹ 424 more variables: OECD <dbl+lbl>, ADMINMODE <dbl+lbl>,\n#   LANGTEST_QQQ <dbl+lbl>, SC001Q01TA <dbl+lbl>, SC013Q01TA <dbl+lbl>,\n#   SC014Q01TA <dbl+lbl>, SC016Q01TA <dbl+lbl>, SC016Q02TA <dbl+lbl>,\n#   SC016Q03TA <dbl+lbl>, SC016Q04TA <dbl+lbl>, SC011Q01TA <dbl+lbl>,\n#   SC002Q01TA <dbl+lbl>, SC002Q02TA <dbl+lbl>, SC211Q01JA <dbl+lbl>,\n#   SC211Q02JA <dbl+lbl>, SC211Q03JA <dbl+lbl>, SC211Q04JA <dbl+lbl>, …\n```\n:::\n:::\n\n\nSimilar to the Student's Questionnaire, let's first filter for Singapore schools.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsch_SG <- sch %>%\n  filter(CNT == \"SGP\")\n\nhead(sch_SG,3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 432\n  CNT             CNTRYID        CNTSCHID CYC   NatCen     STRATUM    SUBNATIO  \n  <chr+lbl>       <dbl+lbl>         <dbl> <chr> <chr+lbl>  <chr+lbl>  <chr+lbl> \n1 SGP [Singapore] 702 [Singapor… 70200001 08MS  070… [Sin… SGP… [SGP… 702… [Sin…\n2 SGP [Singapore] 702 [Singapor… 70200002 08MS  070… [Sin… SGP… [SGP… 702… [Sin…\n3 SGP [Singapore] 702 [Singapor… 70200003 08MS  070… [Sin… SGP… [SGP… 702… [Sin…\n# ℹ 425 more variables: REGION <dbl+lbl>, OECD <dbl+lbl>, ADMINMODE <dbl+lbl>,\n#   LANGTEST_QQQ <dbl+lbl>, SC001Q01TA <dbl+lbl>, SC013Q01TA <dbl+lbl>,\n#   SC014Q01TA <dbl+lbl>, SC016Q01TA <dbl+lbl>, SC016Q02TA <dbl+lbl>,\n#   SC016Q03TA <dbl+lbl>, SC016Q04TA <dbl+lbl>, SC011Q01TA <dbl+lbl>,\n#   SC002Q01TA <dbl+lbl>, SC002Q02TA <dbl+lbl>, SC211Q01JA <dbl+lbl>,\n#   SC211Q02JA <dbl+lbl>, SC211Q03JA <dbl+lbl>, SC211Q04JA <dbl+lbl>,\n#   SC211Q05JA <dbl+lbl>, SC211Q06JA <dbl+lbl>, SC018Q01TA01 <dbl+lbl>, …\n```\n:::\n:::\n\n\nA quick look at the data using `head()` shows that the table contains column *CNTSCHID* that we can use to perform a join with our *stu_SG_lean* table to patch in additional variables.\n\nAfter perusing through the [**Codebook**](https://webfs.oecd.org/pisa2022/CY08MSP_CODEBOOK_5thDecember23.xlsx), the following variables are selected for further analysis:\n\n+-----------+---------------+-----------------------+-----------+----------------------------------+\n| Category  | Variable Name | Description/Question  | Type      | Encoding Scheme                  |\n+===========+===============+=======================+===========+==================================+\n| School    | SCHLTYPE      | School type           | NUM       | 1 - Private independent          |\n|           |               |                       |           |                                  |\n|           |               |                       |           | 2 - Private Government-dependent |\n|           |               |                       |           |                                  |\n|           |               |                       |           | 3 - Public                       |\n+-----------+---------------+-----------------------+-----------+----------------------------------+\n| School    | STRATIO       | Student-teacher ratio | NUM       |                                  |\n+-----------+---------------+-----------------------+-----------+----------------------------------+\n\n: {tbl-colwidths=\"\\[10,10,30,5,45\\]\" .striped .hover}\n\n#### 4.5.2.1 Narrowing School Data\n\nThe code chunk below performs the following purpose:\n\n-   [`select()`](https://benwhalley.github.io/just-enough-r/selecting-columns.html) extracts using the names of columns we have identified.\n-   [`rename()`](https://dplyr.tidyverse.org/reference/rename.html) changes the names of individual variables so they are more intuitive.\n-   [`mutate()`](https://dplyr.tidyverse.org/reference/mutate.html) replaces 'SchType' from numeric type to factor type using [`as.factor()`](https://www.rdocumentation.org/packages/h2o/versions/2.4.3.11/topics/as.factor) and replaces 'SchID' numeric to character data type with [`as.character()`](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/character).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsch_SG_lean <- sch_SG %>% \n  select(CNTSCHID, SCHLTYPE, STRATIO) %>% \n  rename(c(SchID=\"CNTSCHID\",\n           SchType=\"SCHLTYPE\",\n           StuTeacher_ratio=\"STRATIO\")) %>% \n  mutate(SchType=as.factor(SchType)) %>%\n  mutate(SchID = as.character(SchID))\n```\n:::\n\n\n#### 4.5.2.2 Recoding School Type\n\n*SchType* is recoded to reflect the type of schools in the education system (Private Independent, Private government-dependent, and public).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsch_SG_lean <- sch_SG_lean %>%\n  mutate(SchType=\n           (recode(SchType, \n                   '1'=\"privindependent\", \n                   '2'=\"privgovdependent\", \n                   '3'=\"public\")))\n```\n:::\n\n\n#### 4.5.2.3 Combining with Students data\n\nNext, the `left_join()` retains all observations that appear in the left (first) data frame, even if they lack a match in the right (second) dataframe. `by=c(\"SchID\"=\"CNTSCHID\")` refers to the key used to perform the match, which are *SchID* from *stu_SG_lean* data and *CNTSCHID* from *sch_SG_lean* data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstu_SG_more <- \n  left_join(stu_SG_lean, \n            sch_SG_lean,\n            by=c(\"SchID\"=\"SchID\")) %>% \n  mutate(StuTeacher_ratio = as.numeric(StuTeacher_ratio))\n```\n:::\n\n\nFinally, `is.na()` function is used to confirm that there are no missing values in our data,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(stu_SG_more))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\nThe first 5 results of the final dataset are displayed below using [kable()](https://www.rdocumentation.org/packages/knitr/versions/1.45/topics/kable) of the **knitr** package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(head(stu_SG_more, n=5), caption = \"Results from the 2022 PISA Student Questionnaire Survey\")\n```\n\n::: {.cell-output-display}\nTable: Results from the 2022 PISA Student Questionnaire Survey\n\n|SchID    |Gender |Immigration_Status |Occupation_Status_Father |Occupation_Status_Mother |Have_Comp |Have_EduSW |Have_Internet |Edu_Mother     |Edu_Father     |Time_HW_Math |Time_HW_Reading |Time_HW_Science | Avg_Math| Avg_Reading|  Avg_Sci|SchType | StuTeacher_ratio|\n|:--------|:------|:------------------|:------------------------|:------------------------|:---------|:----------|:-------------|:--------------|:--------------|:------------|:---------------|:---------------|--------:|-----------:|--------:|:-------|----------------:|\n|70200052 |Female |Native             |Unemployed               |Employed                 |Yes       |Yes        |Yes           |Tertiary       |Post-Secondary |<31          |<31             |31-60           | 605.2533|    667.4296| 639.7873|public  |          13.7528|\n|70200134 |Male   |Native             |Employed                 |Employed                 |Yes       |Yes        |Yes           |Post-Secondary |Post-Secondary |61-120       |31-60           |61-120          | 689.9528|    627.6078| 672.0703|public  |          11.1354|\n|70200112 |Male   |Native             |Unemployed               |Unemployed               |Yes       |No         |Yes           |Secondary      |Secondary      |31-60        |61-120          |61-120          | 676.7768|    582.9252| 660.0384|public  |          12.8729|\n|70200004 |Male   |Native             |Employed                 |Employed                 |Yes       |Yes        |Yes           |Post-Secondary |Post-Secondary |61-120       |<31             |31-60           | 401.0528|    361.3969| 343.6425|public  |          13.2381|\n|70200152 |Female |Native             |Employed                 |Employed                 |Yes       |Yes        |Yes           |Post-Secondary |Post-Secondary |>120         |61-120          |>120            | 436.1151|    475.6763| 479.2390|public  |          10.6391|\n:::\n:::\n\n\n# 5 Univariate Analysis\n\nThe next few plots helps visualise the key variables used for this study before diving into Exploratory Data Analysis.\n\n## 5.1 Target Variables: Subject Performance\n\nWhen exploring new data, one of the first steps is to look at the distributions of the target variables. In this case, our targets are the scores for Science, Reading, and Math. A histogram wih a boxplot can show how the scores are distribution among the students.\n\nNote that the axis limits are consistent across the three subjects to facilitate comparison. This ensures that when a user navigates between various tabs, the scales remain identical. This uniformity in scale is crucial as it allows for more accurate and straightforward comparison. Users can easily compare data across different subjects without the need to adjust mentally for variation in scale.\n\n::: panel-tabset\n## Math\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Sets theme for the rest of the plots\npacman::p_load(urbnthemes)\nset_urbn_defaults(style = \"print\")\n\n# Calculating the mean, median, min and max\nmean_math <- round(mean(stu_SG_more$Avg_Math),0)\nmedian_math <- round(median(stu_SG_more$Avg_Math),0)\nmin_math <- round(min(stu_SG_more$Avg_Math),0)\nmax_math <- round(max(stu_SG_more$Avg_Math),0)\nleftwhisk_math <- round(quantile(stu_SG_more$Avg_Math, probs = .25)-1.5*IQR(stu_SG_more$Avg_Math),0)\n\n# Histogram\nhist_math <- \n  ggplot(\n    stu_SG_more, \n    aes(x = Avg_Math)\n  ) +\n  geom_histogram(\n    bins = 25,\n    color = \"#f5f5f5\",\n    fill=\"#c7c8cc\"\n  ) +\n  scale_x_continuous(\n    breaks = scales::pretty_breaks(n = 5),\n    \n    # Set same limits for both plots for consistency\n    limits = c(150,950), \n  ) + \n  geom_vline(\n    aes(xintercept = median_math),\n    colour=\"#595DE5\", \n    linewidth = 0.7, \n    linetype = \"dashed\"\n  ) +\n  annotate(\n    geom = \"text\", \n    x = 660, \n    y = 870,\n    label = paste0(\"Median = \", median_math),\n    color=\"#595DE5\"\n  ) +\n  geom_vline(\n    aes(xintercept = mean_math),\n    colour=\"#e0218a\", \n    linewidth = 0.7, \n    linetype = \"dashed\"\n  ) +\n  annotate(\n    geom = \"text\", \n    x = 535, \n    y = 870,\n    label = paste0(\"Mean = \", mean_math),\n    color=\"#e0218a\"\n  ) +  \n  labs(x = NULL, y = NULL\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.y = element_blank(),\n    panel.grid.major = element_blank(),\n    plot.background = element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n  )\n\n# Boxplot\nbox_math <- \n  ggplot(\n    stu_SG_more, \n    aes(y = Avg_Math, x=\"\")\n  ) + \n  geom_boxplot(\n    fill=\"#c7c8cc\",\n    outlier.colour=\"#d18a7d\", \n    outlier.shape=16,\n    outlier.size=1, \n    notch=FALSE\n  ) + \n  stat_summary(geom = 'point',\n               fun.y='mean',\n               colour = '#e0218a',\n               size=4) +\n  coord_flip() + \n  \n    #Annotate with amounts to show range\n  annotate(\n    geom = \"text\", \n    x = 0.5, \n    y = min_math,\n    label = paste0(min_math),\n    color = \"#d18a7d\"\n  ) + \n   annotate(\n    geom = \"text\", \n    x = 0.5, \n    y = leftwhisk_math,\n    label = paste0(leftwhisk_math),\n    color = \"#34414E\"\n  ) +\n  annotate(\n    geom = \"text\", \n    x = 0.5, \n    y = max_math,\n    label = paste0(max_math),\n    color = \"#34414E\"\n  ) + \n  \n  labs(\n    title = \"Symmetrical Distribution of Average Math Scores\",\n     y = \"\", \n    x = \"\"\n  ) + \n   scale_y_continuous(\n    limits = c(150,950), \n  ) +\n  \n  stat_boxplot(\n    geom=\"errorbar\", \n    width=0.5\n  ) + \n  theme_minimal() +\n  theme(\n    axis.text = element_blank(), \n    axis.ticks = element_blank(),\n    panel.grid.major = element_blank(),\n     plot.background = element_rect(\n       fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n  )\n\nhbox_math <- (box_math / hist_math) + \n        plot_layout(heights = c(1, 3.5)) #< Scale layout to keep boxplot height shorter\n\nhbox_math & theme(plot.background = element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\"))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n## Reading\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Calculating the mean, median, min and max\nmean_reading <- round(mean(stu_SG_more$Avg_Reading),0)\nmedian_reading <- round(median(stu_SG_more$Avg_Reading),0)\nmin_reading <- round(min(stu_SG_more$Avg_Reading),0)\nmax_reading <- round(max(stu_SG_more$Avg_Reading),0)\nleftwhisk_reading <- round(quantile(stu_SG_more$Avg_Reading, probs = .25)-1.5*IQR(stu_SG_more$Avg_Reading),0)\n\n# Histogram\nhist_reading <- \n  ggplot(\n    stu_SG_more, \n    aes(x = Avg_Reading)\n  ) +\n  geom_histogram(\n    bins = 25,\n    color = \"#f5f5f5\",\n    fill=\"#c7c8cc\"\n  ) +\n  scale_x_continuous(\n    breaks = scales::pretty_breaks(n = 5),\n    \n    # Set same limits for both plots for consistency\n    limits = c(150,950), \n  ) + \n  geom_vline(\n    aes(xintercept = median_reading),\n    colour=\"#595DE5\", \n    linewidth = 0.7, \n    linetype = \"dashed\"\n  ) +\n  annotate(\n    geom = \"text\", \n    x = median_reading+80, \n    y = 920,\n    label = paste0(\"Median = \", median_reading),\n    color=\"#595DE5\"\n  ) +\n  geom_vline(\n    aes(xintercept = mean_reading),\n    colour=\"#e0218a\", \n    linewidth = 0.7, \n    linetype = \"dashed\"\n  ) +\n  annotate(\n    geom = \"text\", \n    x = mean_reading-50, \n    y = 920,\n    label = paste0(\"Mean = \", mean_reading),\n    color=\"#e0218a\"\n  ) +  \n  labs(x = NULL, y = NULL\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.y = element_blank(),\n    panel.grid.major = element_blank(),\n    plot.background = element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n  )\n\n# Boxplot\nbox_reading <- \n  ggplot(\n    stu_SG_more, \n    aes(y = Avg_Reading, x=\"\")\n  ) + \n  geom_boxplot(\n    fill=\"#c7c8cc\",\n    outlier.colour=\"#d18a7d\", \n    outlier.shape=16,\n    outlier.size=1, \n    notch=FALSE\n  ) + \n  stat_summary(geom = 'point',\n               fun.y='mean',\n               colour = '#e0218a',\n               size=4) +\n  coord_flip() + \n  \n    #Annotate with amounts to show range\n  annotate(\n    geom = \"text\", \n    x = 0.5, \n    y = min_reading,\n    label = paste0(min_reading),\n    color = \"#d18a7d\"\n  ) + \n   annotate(\n    geom = \"text\", \n    x = 0.5, \n    y = leftwhisk_reading,\n    label = paste0(leftwhisk_reading),\n    color = \"#34414E\"\n  ) +\n  annotate(\n    geom = \"text\", \n    x = 0.5, \n    y = max_reading,\n    label = paste0(max_reading),\n    color = \"#34414E\"\n  ) + \n  \n  labs(\n    title = \"Symmetrical Distribution of Average Reading Scores\",\n     y = \"\", \n    x = \"\"\n  ) + \n   scale_y_continuous(\n    limits = c(150,950), \n  ) +\n  \n  stat_boxplot(\n    geom=\"errorbar\", \n    width=0.5\n  ) + \n  theme_minimal() +\n  theme(\n    axis.text = element_blank(), \n    axis.ticks = element_blank(),\n    panel.grid.major = element_blank(),\n     plot.background = element_rect(\n       fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n  )\n\nhbox_reading <- (box_reading / hist_reading) + \n        plot_layout(heights = c(1, 3.5)) #< Scale layout to keep boxplot height shorter\n\nhbox_reading & theme(plot.background = element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\"))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n## Science\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Calculating the mean, median, min and max\nmean_sci <- round(mean(stu_SG_more$Avg_Sci),0)\nmedian_sci <- round(median(stu_SG_more$Avg_Sci),0)\nmin_sci <- round(min(stu_SG_more$Avg_Sci),0)\nmax_sci <- round(max(stu_SG_more$Avg_Sci),0)\nleftwhisk_sci <- round(quantile(stu_SG_more$Avg_Sci, probs = .25)-1.5*IQR(stu_SG_more$Avg_Sci),0)\n\n# Histogram\nhist_sci <- \n  ggplot(\n    stu_SG_more, \n    aes(x = Avg_Sci)\n  ) +\n  geom_histogram(\n    bins = 25,\n    color = \"#f5f5f5\",\n    fill=\"#c7c8cc\"\n  ) +\n  scale_x_continuous(\n    breaks = scales::pretty_breaks(n = 5),\n    \n    # Set same limits for both plots for consistency\n    limits = c(150,950), \n  ) + \n  geom_vline(\n    aes(xintercept = median_sci),\n    colour=\"#595DE5\", \n    linewidth = 0.7, \n    linetype = \"dashed\"\n  ) +\n  annotate(\n    geom = \"text\", \n    x = median_sci+70, \n    y = 940,\n    label = paste0(\"Median = \", median_sci),\n    color=\"#595DE5\"\n  ) +\n  geom_vline(\n    aes(xintercept = mean_sci),\n    colour=\"#e0218a\", \n    linewidth = 0.7, \n    linetype = \"dashed\"\n  ) +\n  annotate(\n    geom = \"text\", \n    x = mean_sci-50, \n    y = 940,\n    label = paste0(\"Mean = \", mean_sci),\n    color=\"#e0218a\"\n  ) +  \n  labs(x = NULL, y = NULL\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.y = element_blank(),\n    panel.grid.major = element_blank(),\n    plot.background = element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n  )\n\n# Boxplot\nbox_sci <- \n  ggplot(\n    stu_SG_more, \n    aes(y = Avg_Sci, x=\"\")\n  ) + \n  geom_boxplot(\n    fill=\"#c7c8cc\",\n    outlier.colour=\"#d18a7d\", \n    outlier.shape=16,\n    outlier.size=1, \n    notch=FALSE\n  ) + \n  stat_summary(geom = 'point',\n               fun.y='mean',\n               colour = '#e0218a',\n               size=4) +\n  coord_flip() + \n  \n  #Annotate with amounts to show range\n  annotate(\n    geom = \"text\", \n    x = 0.5, \n    y = min_sci,\n    label = paste0(min_sci),\n    color = \"#d18a7d\"\n  ) + \n   annotate(\n    geom = \"text\", \n    x = 0.5, \n    y = leftwhisk_sci,\n    label = paste0(leftwhisk_sci),\n    color = \"#34414E\"\n  ) +\n  annotate(\n    geom = \"text\", \n    x = 0.5, \n    y = max_sci,\n    label = paste0(max_sci),\n    color = \"#34414E\"\n  ) + \n  \n  labs(\n    title = \"Symmetrical Distribution of Average Science Scores\",\n     y = \"\", \n    x = \"\"\n  ) + \n   scale_y_continuous(\n    limits = c(150,950), \n  ) +\n  \n  stat_boxplot(\n    geom=\"errorbar\", \n    width=0.5\n  ) + \n  theme_minimal() +\n  theme(\n    axis.text = element_blank(), \n    axis.ticks = element_blank(),\n    panel.grid.major = element_blank(),\n     plot.background = element_rect(\n       fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n  )\n\nhbox_sci <- (box_sci / hist_sci) + \n        plot_layout(heights = c(1, 3.5)) #< Scale layout to keep boxplot height shorter\n\nhbox_sci & theme(plot.background = element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\"))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n:::\n\n## 5.2 Time Spent on Homework\n\nBar charts can be used to represent frequencies of different categories, appropriate for categorical variables that use a nominal or ordinal scale of measurement. Adding direct labels can increase accessibility of a bar graph and reduce the \"chart junk\" since grid lines, axis labels, and even axis titles become obsolete. Ordering bar charts for categorical values with no internal order can help the reader focus on the largest and smallest groups. In the plot below, arranging according to increasing time frame would make sense as the variable follows the ordinal scale.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\np2_hwt_reading <- ggplot(data = stu_SG_filtered, \n       aes(x = Time_HW_Reading)) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 2600) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \\n\", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.2,\n      size=3) +  \n    labs(x = \"\",\n         y = \"\",\n         title=\"Reading\") + \n    theme(\n      panel.grid.major = element_blank(), \n      plot.title = element_text(size=9, face=\"bold\"),\n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),\n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    ) \n\np2_hwt_math <- ggplot(data = stu_SG_filtered, \n       aes(x = Time_HW_Math)) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 2600) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \\n\", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.2,\n      size=3) +  \n    labs(x = \"\",\n         y = \"\",\n         title=\"Math\") + \n    theme(\n      panel.grid.major = element_blank(), \n      plot.title = element_text(size=9, face=\"bold\"),\n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),\n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    ) \n\np2_hwt_sci <- ggplot(data = stu_SG_filtered, \n       aes(x = Time_HW_Science)) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 2600) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \\n\", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.2,\n      size=3) +  \n    labs(x = \"\",\n         y = \"\",\n         title=\"Science\") + \n    theme(\n      panel.grid.major = element_blank(), \n      plot.title = element_text(size=9, face=\"bold\"),\n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),\n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    ) \n\n\np2_hwt_math + p2_hwt_reading + p2_hwt_sci +\n  plot_layout(widths=c(1,1,1)) +\n  plot_annotation(title=\"Time Spent on Homework in mins\", \n                  theme=theme(plot.title = element_text(hjust = 0),\n                  plot.background = element_rect(fill=\"#f5f5f5\", colour = \"#f5f5f5\"),\n                  panel.border = element_blank()))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\n::: {.brainbox .brain data-latex=\"brain\"}\n**Observations**\n\n-   Both Science and Math seem to be more spread out to cover more timeframes.\n-   The bar chart is clustered around the lower end of time spent on homework for Reading.\n-   This is interesting because median and mean Reading scores are the lowest among the 3 subjects.\n:::\n\n## 5.3 Student Characteristics\n\nTo calculate percentage values, we can either create the labels first or on the fly. In the last and next few plots, the labels are added with the help of `geom_text()` to add text as marker labels, [`after_stat()`](https://ggplot2.tidyverse.org/reference/aes_eval.html) to count the frequency, and `paste0` for concatenation.\n\n`geom_text()` comes with arguments that help you to align and position text labels. `hjust` and `vjust` refers to the horizontal and vertical justification to align text, while `nudge_x` and `nudge_y` offset text from points horizontally and vertically.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\np_gender <-\n  ggplot(data = stu_SG_more, \n       aes(x = reorder(Gender, Gender, function(x)-length(x)))) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 5200) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.5,\n      size=3) +\n    labs(x = \"\",\n         y = \"\",\n         title = \"Gender: \") + \n    theme(\n      plot.title = element_text(size=9, face=\"bold\"),\n      panel.grid.major = element_blank(), \n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),   \n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    ) \n\np_immig <-\n  ggplot(data = stu_SG_more, \n       aes(x = Immigration_Status)) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 5200) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.5,\n      size=3) +\n    labs(x = \"\",\n         y = \"\",\n         title = \"Immigration Status: \") + \n    theme(\n      plot.title = element_text(size=9, face=\"bold\"),\n      panel.grid.major = element_blank(), \n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),     \n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    ) \n\n\np_havecomp <- ggplot(data = stu_SG_more, \n       aes(x = Have_Comp)) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 6600) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.5,\n      size=3) +\n    labs(x = \"\",\n         y = \"\",\n         title=\"Computer: \") + \n    theme(\n      plot.title = element_text(size=9, face=\"bold\"),\n      panel.grid.major = element_blank(), \n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),   \n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    ) \n\np_haveEduSW <- ggplot(data = stu_SG_more, \n       aes(x = Have_EduSW)) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 6600) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.5,\n      size=3) +\n    labs(x = \"\",\n         y = \"\",\n         title=\"Educational Software: \") + \n    theme(\n      panel.grid.major = element_blank(), \n      plot.title = element_text(size=9, face=\"bold\"),\n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),\n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\",)\n    ) \n\np_haveInternet <- ggplot(data = stu_SG_more, \n       aes(x = Have_Internet)) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 6600) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.5,\n      size=3) +\n    labs(x = \"\",\n         y = \"\",\n         title=\"Internet: \") + \n    theme(\n      panel.grid.major = element_blank(), \n      plot.title = element_text(size=9, face=\"bold\"),\n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),\n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    ) \n\n\np_access <- (p_havecomp + p_haveEduSW + p_haveInternet) \np_stuchar <- (p_gender + p_immig) / p_access +\n              plot_layout(widths = c(1,1))+\n              plot_annotation(title=\"Equitable gender distribution, majority native Singaporeans,\\n and high access to educational hools at home\", \n                              theme=theme(plot.title = element_text(hjust = 0),\n                                          plot.background = element_rect(fill=\"#f5f5f5\", colour = \"#f5f5f5\"),\n                                          panel.border = element_blank()))\n\n\np_stuchar\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n::: {.brainbox .brain data-latex=\"brain\"}\n**Observations**\n\n-   The students responses are almost evenly distributed between males and females. Uneven distributions seen across Immigration Status, and home access to educational resources like computers, educational software, and internet.\n-   Native Singaporeans make up the bulk of the survey responses.\n-   Most students have access to educational tools/resources such as computer, educational software, and the internet from home.\n:::\n\n## 5.4 Parents Occupational & Educational Status\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\np_osf <- ggplot(data = stu_SG_more, \n       aes(x = Occupation_Status_Father)) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 6110) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.5,\n      size=3) +\n    labs(x = \"\",\n         y = \"\",\n         title=\"Father\") + \n    theme(\n      panel.grid.major = element_blank(), \n      plot.title = element_text(size=9, face=\"bold\"),\n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),\n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    ) \n\np_osm <- ggplot(data = stu_SG_more, \n       aes(x = Occupation_Status_Mother)) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 6110) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.5,\n      size=3) +\n    labs(x = \"\",\n         y = \"\",\n         title=\"Mother\") + \n    theme(\n      panel.grid.major = element_blank(), \n      plot.title = element_text(size=9, face=\"bold\"),\n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),\n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    ) \n\np_eduF <- ggplot(data = stu_SG_more, \n       aes(x = Edu_Father)) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 6110) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.5,\n      size=3) +\n    labs(x = \"\",\n         y = \"\",\n         title=\"Father\") + \n    theme(\n      panel.grid.major = element_blank(), \n      plot.title = element_text(size=9, face=\"bold\"),\n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),\n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    ) \n\np_eduM <- ggplot(data = stu_SG_more, \n       aes(x = Edu_Mother)) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 6110) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.5,\n      size=3) +\n    labs(x = \"\",\n         y = \"\",\n         title=\"Mother\") + \n    theme(\n      panel.grid.major = element_blank(), \n      plot.title = element_text(size=9, face=\"bold\"),\n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),\n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    )  \n\np_eduF + p_osf + p_eduM + p_osm +\n  plot_layout(widths=c(2,1)) +\n  plot_annotation(title = \"Most students have parents who are employed, with nearly half of them having tertiary education.\", \n                  subtitle=\"Similar patterns in education and employment among fathers and mothers\", \n                  theme=theme(plot.title = element_text(hjust = 0),\n                  plot.background = element_rect(fill=\"#f5f5f5\", colour = \"#f5f5f5\"),\n                  panel.border = element_blank()))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n::: {.brainbox .brain data-latex=\"brain\"}\n**Observations**\n\n-   There are more parents with post-secondary and tertiary education compared to lower levels of educational attainment. Employed parents make up the majority of the responses.\n\n-   The split between educational levels and employment status are similar between Fathers and Mothers. Both have the highest proportion (almost half) with Tertiary education and most parents are employed.\n\n-   Unemployed father are almost twice as many as unemployed mothers.\n:::\n\n## 5.5 School Characteristics\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\np_schtype <- ggplot(data = stu_SG_more, \n       aes(x = SchType )) +\n    geom_bar(fill=\"#c7c8cc\")+\n    ylim(0, 6110) + \n    geom_text(stat=\"count\", \n      aes(label=paste0(after_stat(count), \", \", \n      round(after_stat(count)/sum(after_stat(count))*100, 1), \"%\")),\n      vjust=-0.5,\n      size=3) +\n    labs(x = \"\",\n         y = \"\",\n         title=\"School Type\") + \n    theme(\n      panel.grid.major = element_blank(), \n      plot.title = element_text(size=9, face=\"bold\"),\n      axis.text.y = element_blank(),\n      axis.title.y = element_blank(),\n      axis.ticks.y = element_blank(),\n      #axis.ticks.x = element_blank(),      \n      plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n    ) \n\n# Calculating the mean, median, min and max\nmean_str <- round(mean(stu_SG_more$StuTeacher_ratio),2)\nmedian_str <- round(median(stu_SG_more$StuTeacher_ratio),2)\nmin_str <- round(min(stu_SG_more$StuTeacher_ratio),2)\nmax_str <- round(max(stu_SG_more$StuTeacher_ratio),2)\nleftwhisk_str <- round(quantile(stu_SG_more$StuTeacher_ratio, probs = .25)-1.5*IQR(stu_SG_more$StuTeacher_ratio),2)\n\n# Histogram\nhist_str <- \n  ggplot(\n    stu_SG_more, \n    aes(x = StuTeacher_ratio)\n  ) +\n  geom_histogram(\n    bins = 25,\n    color = \"#f5f5f5\",\n    fill=\"#c7c8cc\"\n  ) +\n  scale_x_continuous(\n    breaks = scales::pretty_breaks(n = 5),\n    \n    # Set same limits for both plots for consistency\n    limits = c(1,100), \n  ) + \n  geom_vline(\n    aes(xintercept = median_str),\n    colour=\"#595DE5\", \n    linewidth = 0.7, \n    linetype = \"dashed\"\n  ) +\n  annotate(\n    geom = \"text\", \n    x = 20, \n    y = 5000,\n    label = paste0(\"Median =\\n\", median_str),\n    color=\"#595DE5\"\n  ) +\n  geom_vline(\n    aes(xintercept = mean_str),\n    colour=\"#e0218a\", \n    linewidth = 0.7, \n    linetype = \"dashed\"\n  ) +\n  annotate(\n    geom = \"text\", \n    x = 5, \n    y = 5000,\n    label = paste0(\"Mean =\\n\", mean_str),\n    color=\"#e0218a\"\n  ) +  \n  labs(x = NULL, y = NULL\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.y = element_blank(),\n    panel.grid.major = element_blank(),\n    plot.background = element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n  )\n\n# Boxplot\nbox_str <- \n  ggplot(\n    stu_SG_more, \n    aes(y = StuTeacher_ratio, x=\"\")\n  ) + \n  geom_boxplot(\n    fill=\"#c7c8cc\",\n    outlier.colour=\"#d18a7d\", \n    outlier.shape=16,\n    outlier.size=1, \n    notch=FALSE\n  ) + \n  stat_summary(geom = 'point',\n               fun.y='mean',\n               colour = '#e0218a',\n               size=2) +\n  coord_flip() + \n  \n  #Annotate with amounts to show range\n  annotate(\n    geom = \"text\", \n    x = 0.5, \n    y = min_str,\n    label = paste0(min_str),\n    color = \"#d18a7d\"\n  ) + \n  annotate(\n    geom = \"text\", \n    x = 0.5, \n    y = max_str,\n    label = paste0(max_str),\n    color = \"#d18a7d\"\n  ) + \n  \n  labs(\n    title = \"Distribution of Student-Teacher Ratio\",\n     y = \"\", \n    x = \"\"\n  ) + \n   scale_y_continuous(\n    limits = c(1,100), \n  ) +\n  \n  stat_boxplot(\n    geom=\"errorbar\", \n    width=0.5\n  ) + \n  theme_minimal() +\n  theme(\n    plot.title = element_text(size=9, face=\"bold\"),\n    axis.text = element_blank(), \n    axis.ticks = element_blank(),\n    panel.grid.major = element_blank(),\n     plot.background = element_rect(\n       fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n  )\n\n\nhbox_str <- (box_str / hist_str) + \n        plot_layout(heights = c(1, 3.5)) #< Scale layout to keep boxplot height shorter\n\n(p_schtype + hbox_str) +\n  plot_layout(widths=c(1,2)) +\n  plot_annotation(title=\"Most Responses from Public Schools Show a 12:1 Student-Teacher Ratio\", \n                  theme=theme(plot.title = element_text(hjust = 0),\n                  plot.background = element_rect(fill=\"#f5f5f5\", colour = \"#f5f5f5\"),\n                  panel.border = element_blank()))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n::: {.brainbox .brain data-latex=\"brain\"}\n**Observations**\n\n-   Responses are mostly from students attending public schools, with less than 10% of responses from private-school goers.\n\n-   The distribution of Student-Teacher ratio is highly skewed to the right, with most of the responses centered around the mean and median Student-Teacher Ratio of 12.\n\n-   There is a large variation in the Student-Teacher Ratio range. Significant outliers on both ends of the scale are noted, particularly on the right tail with a ratio of 100 students to 1 teacher.\n\n-   To increase variability and to make the patterns in the data more interpretable, we can consider performing a log transformation to reduce the skewness of the variable.\n\n**Design Consideration for EDA**\n\n-   Interestingly, the boxplot was able to highlight the outliers on the far right end of the scale while the histogram was unable to capture this due to the scale/range of the y-axis even though the y-axis starts from 0. Graphically, the boxplot is a much better tool for detecting outliers in such cases.\n\n-   Yet, boxplots are not very helpful at conveying frequencies. It is hard to tell the sample size through conventional boxplots.\n:::\n\n# 6 Exploratory Data Analysis\n\n## 6.1 Comparing distribution of subject performance\n\nRidgeline plots are a way to express the distribution of the data for several categorical variables. The code chunk below uses `geom_density_ridges()` to show the distribution of scores by subject. Each curve gives the appropriate probability density function, where the area under the curve is 1.\n\nFigure below is plotted by mapping the probabilities calculated by using `stat(ecdf)` which represent the empirical cumulative density function for the distribution of each subject score. When used as a fill aesthetic in a plot, it can create visual representation where areas of the plot that are closer to the median have a different colour intensity than areas that are further away. This is particularly useful for highlighting the central tendency and dispersion of data in a cumulative distribution plot.\n\n`pivot_longer()` is used to pivot the subject scores into rows from its separate columns.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nstu_SG_more_long <- \n  stu_SG_more %>% \n  pivot_longer(cols = starts_with(\"Avg\"),\n               names_to = \"subject\",\n               names_prefix=\"Avg_\",\n               values_to=\"score\")\n\nggplot(data= stu_SG_more_long,\n        aes(x = score, \n            y = subject, \n           fill = 0.5-abs(0.5-after_stat(ecdf)))\n       )+ \n  geom_density_ridges_gradient(\n                     alpha = 0.8,\n                     scale = 2,\n                     geom = \"density_ridges_gradient\", \n                     calc_ecdf = TRUE) + \n  scale_fill_gradientn(colors = c(\"#ecc9d0\", \"#e0218a\")) +\n  #guides(color = \"none\", fill = \"none\") + \n  labs(x = \"Score\", y = NULL, title = \"Median score for Math higher than Science and Reading.\", \n         subtitle=\"Symmetrical curves appear to resemble Normal distributions across subject.\")+\n  theme(legend.position = \"right\",\n        legend.direction = \"vertical\",\n          plot.title = element_text(size = 12, face = \"bold\"),\n          plot.subtitle = element_text(size = 9),\n          plot.caption = element_text(size = rel(0.8)),\n          axis.text.y = element_text(size = rel(0.9)),\n          plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n          )\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\n::: {.nursebox .nurse data-latex=\"nurse\"}\n**Insights**\n\n-   The most probable scores are brighter (in hot pink).\n\n-   Here we can start to see that Math has the highest median among the 3 subjects.\n\n-   Range and distribution of the 3 subject scores appear to be quite similar.\n:::\n\nNow that we understand the basics of the data a bit more, let's look more into their interaction with other variables.\n\n## 6.2 Comparing scores against time spent on homework between genders\n\nA diverging plot is used to facilitate comparison between male and female students. `gganimate()` helps transition as amount of time spent on homework increases. `transition_manual()` animates the plot over the *Time_HW_Math* variable and `y = -..density..` is used to create the diverging effect. This can allow us to detect changes or trends in our dataset.\n\nIdeally, I would like to include a mean line or a textbox to indicate the changing mean score for each gender at each timeframe and to put all 3 animations side by side, but I haven't managed to figure that out yet.\n\n::: panel-tabset\n## Math\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\npyr_math <- \n  ggplot(data = stu_SG_more,\n            aes(x = Avg_Math, group=Time_HW_Math)) +\n  # Math + Male\n  geom_density(data = subset(stu_SG_more, Gender==\"Male\"),\n               aes(x = Avg_Math,\n                   y=-..density..),\n               fill=\"#73b2c4\",\n               color=\"#73b2c4\",\n               alpha=0.5)+\n  # Math + Female\n  geom_density(data = subset(stu_SG_more, Gender==\"Female\"),\n               aes(x = Avg_Math,\n                   y=..density..),\n               fill=\"#f27279\",\n               colour=\"#f27279\",\n               alpha=0.5)+\n    guides(fill = guide_legend(reverse = TRUE)) +\n    theme_minimal() +\n    theme(legend.position = \"bottom\",\n          plot.title = element_markdown(size = 12, face = \"bold\"),\n          plot.subtitle = element_text(size = rel(0.8)),\n          plot.caption = element_text(size = rel(0.8)),\n          axis.text.y = element_text(size = rel(0.9)),\n          axis.text.x = element_blank(),\n          axis.title.x = element_blank(),\n          plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n          ) +\n  scale_x_continuous(breaks = seq(150,950,100),\n                     labels = seq(150,950,100)) +\n  scale_y_continuous(breaks = -1:1,\n                     labels = abs(-1:1)) +\n    labs(x = \"\", y = NULL, title = \"Better math scores for <span style='color: #73b2c4;'>males</span>, cyclic trends for both <span style='color: #f27279;'>females</span> and<br><span style='color: #73b2c4;'>males</span>\" ,\n         subtitle = \"Time spent on homework: {current_frame} minutes\",\n         fill = \"Gender\") +\n        coord_flip(clip=\"off\")+\n  annotate(\n    geom = \"text\", \n    x = 780, \n    y = -0.003,\n    label = \"Male\",\n    color = \"#4472af\")+\n      \n    annotate(\n    geom = \"text\", \n    x = 780, \n    y = 0.003,\n    label = \"Female\",\n    color = \"#e0218a\")\n\n\npyr_math +\n  transition_manual(factor(Time_HW_Math, c(\"<31\", \"31-60\", \"61-120\", \">120\"))) +\n  ease_aes(\"linear\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-39-1.gif)\n:::\n:::\n\n\n## Reading\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\npyr_reading <- \n  ggplot(data = stu_SG_more,\n            aes(x = Avg_Reading, group=Time_HW_Reading)) +\n  # Reading + Male\n  geom_density(data = subset(stu_SG_more, Gender==\"Male\"),\n               aes(y=-..density..),\n               fill=\"#73b2c4\",\n               color=\"#73b2c4\",\n               alpha=0.5)+\n  # Reading + Female\n  geom_density(data = subset(stu_SG_more, Gender==\"Female\"),\n               aes(y=..density..),\n               fill=\"#f27279\",\n               colour=\"#f27279\",\n               alpha=0.5)+\n    guides(fill = guide_legend(reverse = TRUE)) +\n    theme_minimal() +\n    theme(legend.position = \"bottom\",\n          plot.title = element_text(size = 12, face = \"bold\"),\n          plot.subtitle = element_text(size = rel(0.8)),\n          plot.caption = element_text(size = rel(0.8)),\n          axis.text.y = element_text(size = rel(0.9)),\n          axis.text.x = element_blank(),\n          axis.title.x = element_blank(),\n          plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n          ) +\n  scale_x_continuous(breaks = seq(150,950,100),\n                     labels = seq(150,950,100)) +\n  scale_y_continuous(breaks = -1:1,\n                     labels = abs(-1:1)) +\n    labs(x = \"\", y = NULL, title = \"Left-tailed distribution for both genders observed where\\nless time is spent on reading homework.\",\n         subtitle = \"Time spent on homework: {current_frame} minutes\",\n         fill = \"Gender\") +\n        coord_flip(clip=\"off\")+\n  annotate(\n    geom = \"text\", \n    x = 780, \n    y = -0.003,\n    label = \"Male\",\n    color = \"#4472af\")+\n      \n    annotate(\n    geom = \"text\", \n    x = 780, \n    y = 0.003,\n    label = \"Female\",\n    color = \"#e0218a\")\n\n\npyr_reading +\n  transition_manual(factor(Time_HW_Reading, c(\"<31\", \"31-60\", \"61-120\", \">120\"))) +\n  ease_aes(\"linear\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-40-1.gif)\n:::\n:::\n\n\n## Science\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\npyr_science <- \n  ggplot(data = stu_SG_more,\n            aes(x = Avg_Sci, group=Time_HW_Science)) +\n  # Science + Male\n  geom_density(data = subset(stu_SG_more, Gender==\"Male\"),\n               aes(y=-..density..),\n               fill=\"#73b2c4\",\n               color=\"#73b2c4\",\n               alpha=0.5)+\n  # Science + Female\n  geom_density(data = subset(stu_SG_more, Gender==\"Female\"),\n               aes(y=..density..),\n               fill=\"#f27279\",\n               colour=\"#f27279\",\n               alpha=0.5)+\n    guides(fill = guide_legend(reverse = TRUE)) +\n    theme_minimal() +\n    theme(legend.position = \"bottom\",\n          plot.title = element_markdown(size = 12, face = \"bold\"),\n          plot.subtitle = element_text(size = rel(0.8)),\n          plot.caption = element_text(size = rel(0.8)),\n          axis.text.y = element_text(size = rel(0.9)),\n          axis.text.x = element_blank(),\n          axis.title.x = element_blank(),\n          plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n          ) +\n  scale_x_continuous(breaks = seq(150,950,100),\n                     labels = seq(150,950,100)) +\n  scale_y_continuous(breaks = -1:1,\n                     labels = abs(-1:1)) +\n    labs(x = \"\", y = NULL, title = \"Higher Science scores across all durations by <span style='color: #73b2c4;'>Males</span>.\",\n         subtitle = \"Time spent on homework: {current_frame} minutes\",\n         fill = \"Gender\") +\n        coord_flip(clip=\"off\")+\n  annotate(\n    geom = \"text\", \n    x = 780, \n    y = -0.003,\n    label = \"Male\",\n    color = \"#4472af\")+\n      \n    annotate(\n    geom = \"text\", \n    x = 780, \n    y = 0.003,\n    label = \"Female\",\n    color = \"#e0218a\")\n\n\npyr_science +\n  transition_manual(factor(Time_HW_Science, c(\"<31\", \"31-60\", \"61-120\", \">120\"))) +\n  ease_aes(\"linear\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-41-1.gif)\n:::\n:::\n\n:::\n\n::: {.nursebox .nurse data-latex=\"nurse\"}\n**Insights**\n\n-   Density ridges are utilized to compare gender differences in relation to the amount of time spent on homework for each subject. This method emphasizes the 'peaks' in the distribution, offering valuable insights into how the distribution's shape and variation between male and female students change with differing homework durations.\n\n-   The plot reveals distinct trends in math scores based on homework duration for both genders. For male students, there is an upward trend in the peak scores as time spent on math homework increases, but this trend shows a decline when exceeding 120 minutes. In contrast, female students' median scores tend to plateau after 31-60 minutes of math homework. Overall, the data indicates that male students generally achieve higher math scores than their female counterparts, regardless of the amount of time invested in math homework.\n\n-   Reading scores display similarity across various homework durations. Interestingly, at lower homework times, the distribution tends to skew left.\n\n-   In science, higher scores are consistently observed for males, regardless of the time spent on science homework.\n:::\n\n## 6.3 Comparing scores against student-teacher ratio and school type\n\nThe scatterplot with marginal density overlay facilitates the comparison of two numerical variables: subject scores and the log-transformed student-teacher ratio, across different school types (private-independent and public). The x-axis represents the math scores, and y-axis represents the log-transformed student-teacher ratio. Each point on the scatterplot represents a student response, with the colour coding distinguishing between private and public school students. Along the right side and top of the scatterplot, density plots represent the distributions of the student-teacher ratio and subject scores, respectively.\n\nThe plot's design adjusts the transparency of the density plot and scatter points using `alpha = 0.3` to allow for an unobstructed view of overlaps. This ensures a clear visualization of each group's distribution while preserving the visibility of underlying patterns. Additionally, mean lines are included to benchmark the average values, aiding in the assessment of how individual data points relate to the overall group averages.\n\n::: panel-tabset\n## Math\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nstu_SG_more <- stu_SG_more %>% \n  mutate(logstr = log(StuTeacher_ratio))\n\npmain <- ggplot(stu_SG_more, \n                aes(x = Avg_Math, y = logstr, color = SchType)) +\n  geom_point(alpha=0.3) +\n  scale_color_manual(values = c(\"#7F948F\",\"#E1C8C4\"))+\ngeom_vline(aes(xintercept=mean_math),\n               color=\"#595DE5\", linewidth=0.8, linetype=\"dashed\") +\n  annotate(\n      \"text\", \n      x = 520, \n      y = 4.2,\n      label = paste(\"Mean Score =\\n\", mean_math),\n      color = \"#595DE5\",\n      size = 2.8\n    ) +\n  geom_hline(aes(yintercept=round(mean(stu_SG_more$logstr, na.rm=T),3)),\n               color=\"red\", linewidth=0.8, linetype=\"dashed\") +  \n  annotate(\n      \"text\", \n      x = 800, \n      y = 3.1,\n      label = paste(\"Mean Ratio =\\n\", round(mean(stu_SG_more$logstr, na.rm=T),3)),\n      color = \"red\",\n      size = 2.8\n    ) +\n      labs(x = \"Math\",\n       y = \"log(Student-\\nTeacher Ratio)\",\n       title = \"Math Scores and Student-Teacher Ratios by School Type\") +\n      theme(\n            axis.title.y = element_text(hjust=1, angle=0),\n            plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\"))\n  \n\n# Marginal densities along x axis\nxdens <- axis_canvas(pmain, axis = \"x\") +\n  geom_density(data = stu_SG_more, aes(x = Avg_Math, fill = SchType),\n               alpha = 0.5, size = 0.2) +\n  scale_fill_manual(values = c(\"#7F948F\",\"#E1C8C4\"))\n\n# Marginal densities along y axis\nydens <- axis_canvas(pmain, axis = \"y\", coord_flip = TRUE) +\n  geom_density(data = stu_SG_more, aes(x = logstr, fill = SchType),\n               alpha = 0.5, size = 0.2) +\n  coord_flip() +\n  scale_fill_manual(values = c(\"#7F948F\",\"#E1C8C4\"))\n\np1 <- insert_xaxis_grob(pmain, xdens, grid::unit(.2, \"null\"), position = \"top\")\np2 <- insert_yaxis_grob(p1, ydens, grid::unit(.2, \"null\"), position = \"right\")\nggdraw(p2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\n## Reading\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\npmainr <- ggplot(stu_SG_more, \n                aes(x = Avg_Reading, y = logstr, color = SchType)) +\n  geom_point(alpha=0.3) +\n  scale_color_manual(values = c(\"#7F948F\",\"#E1C8C4\"))+\ngeom_vline(aes(xintercept=mean_reading),\n               color=\"#595DE5\", linewidth=0.8, linetype=\"dashed\") +\n  annotate(\n      \"text\", \n      x = mean_reading -80, \n      y = 4,\n      label = paste(\"Mean Score =\\n\", mean_reading),\n      color = \"#595DE5\",\n      size = 2.8\n    ) +\n  geom_hline(aes(yintercept=round(mean(stu_SG_more$logstr, na.rm=T),3)),\n               color=\"red\", linewidth=0.8, linetype=\"dashed\") +  \n  annotate(\n      \"text\", \n      x = 770, \n      y = 3,\n      label = paste(\"Mean Ratio =\\n\", round(mean(stu_SG_more$logstr, na.rm=T),3)),\n      color = \"red\",\n      size = 2.8\n    ) +\n      labs(x = \"Reading\",\n       y = \"log(Student-\\nTeacher Ratio)\",\n       title = \"Reading Scores and Student-Teacher Ratios by School Type\") +\n      theme(\n            axis.title.y = element_text(hjust=1, angle=0),\n            plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")) +\n    annotate(\n    geom = \"curve\", x = 690, y = 4, xend = 630, yend = 3.3, \n    curvature = .3, arrow = arrow(length = unit(2, \"mm\"))\n  ) +\n  annotate(geom = \"text\", x = 700, y = 4, label = \"higher concentration of\\nprivate school students\", hjust = \"left\", size= 2)  \n    \n  \n\n# Marginal densities along x axis\nxdensr <- axis_canvas(pmain, axis = \"x\") +\n  geom_density(data = stu_SG_more, aes(x = Avg_Reading, fill = SchType),\n               alpha = 0.5, size = 0.2) +\n  scale_fill_manual(values = c(\"#7F948F\",\"#E1C8C4\"))\n\n# Marginal densities along y axis\n# Need to set coord_flip = TRUE, if you plan to use coord_flip()\nydensr <- axis_canvas(pmain, axis = \"y\", coord_flip = TRUE) +\n  geom_density(data = stu_SG_more, aes(x = logstr, fill = SchType),\n               alpha = 0.5, size = 0.2) +\n  coord_flip() +\n  scale_fill_manual(values = c(\"#7F948F\",\"#E1C8C4\"))\n\np1r <- insert_xaxis_grob(pmainr, xdensr, grid::unit(.2, \"null\"), position = \"top\")\np2r <- insert_yaxis_grob(p1r, ydensr, grid::unit(.2, \"null\"), position = \"right\")\nggdraw(p2r)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\n## Science\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\npmains <- ggplot(stu_SG_more, \n                aes(x = Avg_Sci, y = logstr, color = SchType)) +\n  geom_point(alpha=0.3) +\n  scale_color_manual(values = c(\"#7F948F\",\"#E1C8C4\"))+\ngeom_vline(aes(xintercept=mean_sci),\n               color=\"#595DE5\", linewidth=0.8, linetype=\"dashed\") +\n  annotate(\n      \"text\", \n      x = mean_sci -80, \n      y = 4,\n      label = paste(\"Mean Score =\\n\", mean_sci),\n      color = \"#595DE5\",\n      size = 2.8\n    ) +\n  geom_hline(aes(yintercept=round(mean(stu_SG_more$logstr, na.rm=T),3)),\n               color=\"red\", linewidth=0.8, linetype=\"dashed\") +  \n  annotate(\n      \"text\", \n      x = 770, \n      y = 3,\n      label = paste(\"Mean Ratio =\\n\", round(mean(stu_SG_more$logstr, na.rm=T),3)),\n      color = \"red\",\n      size = 2.8\n    ) +\n      labs(x = \"Science\",\n       y = \"log(Student-\\nTeacher Ratio)\",\n       title = \"Science Scores and Student-Teacher Ratios by School Type\") +\n      theme(\n            axis.title.y = element_text(hjust=1, angle=0),\n            plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")) +\n    annotate(\n    geom = \"curve\", x = 690, y = 4, xend = 630, yend = 3.3, \n    curvature = .3, arrow = arrow(length = unit(2, \"mm\"))\n  ) +\n  annotate(geom = \"text\", x = 700, y = 4, label = \"higher concentration of\\nprivate school students\", hjust = \"left\", size= 2)  \n  \n  \n\n# Marginal densities along x axis\nxdenss <- axis_canvas(pmain, axis = \"x\") +\n  geom_density(data = stu_SG_more, aes(x = Avg_Sci, fill = SchType),\n               alpha = 0.5, size = 0.2) +\n  scale_fill_manual(values = c(\"#7F948F\",\"#E1C8C4\"))\n\n# Marginal densities along y axis\n# Need to set coord_flip = TRUE, if you plan to use coord_flip()\nydenss <- axis_canvas(pmain, axis = \"y\", coord_flip = TRUE) +\n  geom_density(data = stu_SG_more, aes(x = logstr, fill = SchType),\n               alpha = 0.5, size = 0.2) +\n  coord_flip() +\n  scale_fill_manual(values = c(\"#7F948F\",\"#E1C8C4\"))\n\np1s <- insert_xaxis_grob(pmains, xdenss, grid::unit(.2, \"null\"), position = \"top\")\np2s <- insert_yaxis_grob(p1s, ydenss, grid::unit(.2, \"null\"), position = \"right\")\nggdraw(p2s)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n:::\n\n::: {.nursebox .nurse data-latex=\"nurse\"}\n**Insights**\n\n-   The unimodal distribution indicated by a single peak in the public schools' student-teacher ratio suggests a uniformity within this group. In contrast, the multimodal density for private schools suggests the presence of distinct groups with different student-teacher ratios.\n\n-   Score distributions across the three subjects are broader among public school students, indicating greater variability in their scores.\n\n-   Private-Independent school students tend to have higher median Reading scores compared to public school students, while public school students seem to perform better in Math and Science.\n\n-   For Reading and Science, a noticeable cluster of private school students (depicted in green) is present in the top rightmost quadrant. These students scored above the mean for these subjects and are associated with a higher student-teacher ratio.\n\n-   There is no clear upward or downward trend visible in the scatterplot, suggesting that there may not be a strong correlation between the student-teacher ratio and math scores. However, a statistical analysis would be necessary to determine the existence and strength of any correlation.\n:::\n\n## 6.4 Comparing scores with socioeconomic status\n\nThe next two visualizations utilize stacked density plots (again!) to explore and compare the influence of each parent's education level and occupational status. Beneath each density plot, a `geom_point` layer is added, which provides a clear indication of the disparity between the two groups' mean scores. This point representation serves as a precise reference for comparing the central tendencies of the distributions, highlighting whether one parent's educational or occupational background tends to be associated with higher or lower mean scores.\n\n### 6.4.1 Education Levels\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Pivot parents education data longer\nparentsedu_long <- \n  stu_SG_more %>% \n  pivot_longer(cols = starts_with(\"Edu_\"),\n               names_to = \"parentsedu\",\n               names_prefix=\"Edu_\",\n               values_to=\"level\") \n\n# Calculate Mean score by parent and educational level and save in new dataframe\nmeans_parentsedu <- \n  parentsedu_long %>% \n  select(parentsedu, level, Avg_Math, Avg_Reading, Avg_Sci) %>% \n  group_by(parentsedu, level) %>% \n  summarise(mean_math = mean(Avg_Math),\n            mean_reading = mean(Avg_Reading),\n            mean_sci = mean(Avg_Sci),\n            .groups = 'drop')\n\n\np_parentsedu_m <-\nggplot(parentsedu_long, \n       aes(x = Avg_Math, y = level,\n           fill = parentsedu,\n           color=parentsedu)) +\n  geom_density_ridges(\n    calc_ecdf = TRUE, \n    scale = 0.8,\n    alpha= 0.3,\n  rel_min_height = 0.01,\n  position = position_nudge(y=0.11)\n  ) +\n  # point for father's mean\n  geom_point(data = subset(means_parentsedu, parentsedu==\"Father\"),\n             aes(x = mean_math, \n                 y = level),\n             alpha=0.4,\n             shape = 21, size = 3, colour = \"#73b2c4\", fill = \"#73b2c4\") +\n  # point for mother's \n  geom_point(data = subset(means_parentsedu, parentsedu==\"Mother\"),\n             aes(x = mean_math, \n                 y = level), \n             alpha=0.4, \n             shape = 23, size = 3, colour = \"#f27279\", fill = \"#f27279\", stroke = .5) +\n  scale_color_manual(name=\"Parent\",\n                        values = c(\"Father\" = \"#73b2c4\", \n                               \"Mother\" = \"#f27279\")) +\n  scale_fill_manual(values = c(\"Father\" = \"#73b2c4\", \n                               \"Mother\" = \"#f27279\")) +\n  labs(\n    x = \"Math\", \n  ) +\n  scale_y_discrete(expand = c(0, 0.1))+\n  guides(color=\"none\") +\n  theme(\n    legend.direction = \"horizontal\",\n    legend.position = \"bottom\",\n    plot.title = element_text(size =12, face = \"bold\"),\n    plot.subtitle = element_text(size = rel(0.8)),\n    plot.caption = element_text(size = rel(0.8)),\n    axis.text.y = element_text(size = rel(0.9)),\n    axis.text.x = element_text(size = rel(0.9)),\n    axis.title.y = element_blank(),\n    plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\") )  \n\np_parentsedu_r <-\nggplot(parentsedu_long, \n       aes(x = Avg_Reading, y = level,\n           fill = parentsedu,\n           color=parentsedu)) +\n  geom_density_ridges(\n    calc_ecdf = TRUE, \n    scale = 0.8,\n    alpha= 0.3,\n  rel_min_height = 0.01,\n  position = position_nudge(y=0.11)\n  ) +\n  # point for father's mean\n  geom_point(data = subset(means_parentsedu, parentsedu==\"Father\"),\n             aes(x = mean_reading, \n                 y = level), \n             alpha=0.4,\n             shape = 21, size = 3, colour = \"#73b2c4\", fill = \"#73b2c4\") +\n  # point for mother's \n  geom_point(data = subset(means_parentsedu, parentsedu==\"Mother\"),\n             aes(x = mean_reading, \n                 y = level), \n             alpha=0.4,\n             shape = 23, size = 3, colour = \"#f27279\", fill = \"#f27279\", stroke = .5) +\n  scale_color_manual(name=\"Parent\",\n                        values = c(\"Father\" = \"#73b2c4\", \n                               \"Mother\" = \"#f27279\")) +\n  scale_fill_manual(values = c(\"Father\" = \"#73b2c4\", \n                               \"Mother\" = \"#f27279\")) +\n  labs(\n    x = \"Reading\", \n  ) +\n  guides(color=\"none\") +\n  scale_y_discrete(expand = c(0, 0.1))+\n  theme(\n    legend.direction = \"horizontal\",\n    legend.position = \"bottom\",\n    plot.title = element_text(size =12, face = \"bold\"),\n    plot.subtitle = element_text(size = rel(0.8)),\n    plot.caption = element_text(size = rel(0.8)),\n    axis.text.x = element_text(size = rel(0.9)),\n    axis.title.y = element_blank(),\n    axis.text.y = element_blank(),\n    plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\") ) +\n  annotate(\n    geom = \"curve\", x = 80, y = 2.0, xend = 280, yend = 2.35, \n    curvature = -.3, arrow = arrow(length = unit(2, \"mm\"))\n  ) +\n  annotate(geom = \"text\", x = 0.1, y = 1.6, label = \"Lower Reading scores\\nwhere their fathers'\\neducation level is\\nlow.\", hjust = \"left\", size= 2)  \n  \np_parentsedu_s <-\nggplot(parentsedu_long, \n       aes(x = Avg_Sci, y = level,\n           fill = parentsedu,\n           color=parentsedu)) +\n  geom_density_ridges(\n    calc_ecdf = TRUE, \n    scale = 0.8,\n    alpha= 0.3,\n  rel_min_height = 0.01,\n  position = position_nudge(y=0.11)\n  ) +\n  # point for father's mean\n  geom_point(data = subset(means_parentsedu, parentsedu==\"Father\"),\n             aes(x = mean_sci, \n                 y = level), \n             alpha=0.4,\n             shape = 21, size = 3, colour = \"#73b2c4\", fill = \"#73b2c4\") +\n  # point for mother's \n  geom_point(data = subset(means_parentsedu, parentsedu==\"Mother\"),\n             aes(x = mean_sci, \n                 y = level), \n             alpha=0.4,\n             shape = 23, size = 3, colour = \"#f27279\", fill = \"#f27279\", stroke = .5) +\n  scale_color_manual(name=\"Parent\",\n                        values = c(\"Father\" = \"#73b2c4\", \n                               \"Mother\" = \"#f27279\")) +\n  scale_fill_manual(values = c(\"Father\" = \"#73b2c4\", \n                               \"Mother\" = \"#f27279\")) +\n  labs(\n    x = \"Science\", \n  ) +\n  guides(color=\"none\") +\n  scale_y_discrete(expand = c(0, 0.1))+\n  theme(\n    legend.direction = \"horizontal\",\n    legend.position = \"bottom\",\n    plot.title = element_text(size =12, face = \"bold\"),\n    plot.subtitle = element_text(size = rel(0.8)),\n    plot.caption = element_text(size = rel(0.8)),\n    axis.text.x = element_text(size = rel(0.9)),\n    axis.title.y = element_blank(),\n    axis.text.y = element_blank(),\n    plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\") )   +\n  annotate(\n    geom = \"curve\", x = 100, y = 5.6\n    , xend = 440, yend = 5.65, \n    curvature = -.3, arrow = arrow(length = unit(2, \"mm\"))\n  ) +\n  annotate(geom = \"text\", x = 0.08, y = 5.4, label = \"Density plots almost\\noverlap completely.\", hjust = \"left\", size= 2)  \n\n(p_parentsedu_m + p_parentsedu_r + p_parentsedu_s) +\n  plot_layout(guides = \"collect\") +\n  plot_annotation(title = \"Higher scores scores with higher parental education levels, similar distributions<br>across <span style='color: #73b2c4;'>fathers'</span> and <span style='color: #f27279;'>mothers</span> education.\",\n                  theme=theme(plot.title = element_markdown(hjust = 0),\n                              plot.subtitle = element_markdown(hjust = 0),\n                  plot.background = element_rect(fill=\"#f5f5f5\", colour = \"#f5f5f5\"),\n                  panel.border = element_blank()))+\n  plot_layout(widths=c(1,1,1))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n\n::: {.nursebox .nurse data-latex=\"nurse\"}\n**Insights**\n\n-   Generally, subject scores improve with increased parental educational attainment. When parents reach higher education levels, the score distributions converge, as evidenced by the nearly overlapping density plots for either parent's educational achievement.\n\n-   However, at lower levels of parental education, disparities become more evident. The density plot associated with the father's education level (indicated in blue) skews to the right, distinctively peering through the overlay. This is corroborated by the leftward shift of the blue points below the curve, signifying that the average scores are lower than those corresponding to the same educational level of the mother. This pattern suggests that a father's lower educational attainment might have a more pronounced inverse impact on student outcomes.\n:::\n\n### 6.4.2 Occupational Status\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Pivot parents occupational status data longer\njobstatus_long <- \n  stu_SG_more %>% \n  pivot_longer(cols = starts_with(\"Occupation_Status_\"),\n               names_to = \"parent\",\n               names_prefix=\"Occupation_Status_\",\n               values_to=\"jobstatus\") \n\n# Calculate Mean score by parent and job status and save in new dataframe\nmeans_parentsjobstat <- \n  jobstatus_long %>% \n  select(parent, jobstatus, Avg_Math, Avg_Reading, Avg_Sci) %>% \n  group_by(parent, jobstatus) %>% \n  summarise(mean_math = mean(Avg_Math),\n            mean_reading = mean(Avg_Reading),\n            mean_sci = mean(Avg_Sci),\n            .groups = 'drop')\n\np_parentsjs_m <-\nggplot(jobstatus_long, \n       aes(x = Avg_Math, y = jobstatus,\n           fill = parent,\n           color=parent)) +\n  geom_density_ridges(\n    calc_ecdf = TRUE, \n  # Reduce space between between education levels \n    scale = 0.8,\n    alpha= 0.3,\n  rel_min_height = 0.01,\n  position = position_nudge(y=0.11)\n  ) +\n  # point for father's mean\n  geom_point(data = subset(means_parentsjobstat, parent==\"Father\"),\n             aes(x = mean_math, \n                 y = jobstatus), \n              alpha=0.4,\n             shape = 21, size = 3, colour = \"#73b2c4\", fill = \"#73b2c4\") +\n  # point for mother's \n  geom_point(data = subset(means_parentsjobstat, parent==\"Mother\"),\n             aes(x = mean_math, \n                 y = jobstatus), \n              alpha=0.4, \n             shape = 23, size = 3, colour = \"#f27279\", fill = \"#f27279\", stroke = .5) +\n  scale_color_manual(name=\"Parent\",\n                        values = c(\"Father\" = \"#73b2c4\", \n                               \"Mother\" = \"#f27279\")) +\n  scale_fill_manual(values = c(\"Father\" = \"#73b2c4\", \n                               \"Mother\" = \"#f27279\")) +\n  labs(\n    x = \"Math\", \n  ) +\n  scale_y_discrete(expand = c(0, 0.1))+\n  guides(color=\"none\") +\n  theme(\n    legend.direction = \"horizontal\",\n    legend.position = \"bottom\",\n    plot.title = element_text(size =12, face = \"bold\"),\n    plot.subtitle = element_text(size = rel(0.8)),\n    plot.caption = element_text(size = rel(0.8)),\n    axis.text.y = element_text(size = rel(0.9)),\n    axis.text.x = element_text(size = rel(0.9)),\n    axis.title.y = element_blank(),\n    plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\") ) \n    \n\np_parentsjs_r <-\nggplot(jobstatus_long, \n       aes(x = Avg_Reading, y = jobstatus,\n           fill = parent,\n           color=parent)) +\n  geom_density_ridges(\n    calc_ecdf = TRUE, \n  # Reduce space between between education levels \n    scale = 0.8,\n    alpha= 0.3,\n  rel_min_height = 0.01,\n  position = position_nudge(y=0.11)\n  ) +\n  # point for father's mean\n  geom_point(data = subset(means_parentsjobstat, parent==\"Father\"),\n             aes(x = mean_reading, \n                 y = jobstatus), \n              alpha=0.4,\n             shape = 21, size = 3, colour = \"#73b2c4\", fill = \"#73b2c4\") +\n  # point for mother's \n  geom_point(data = subset(means_parentsjobstat, parent==\"Mother\"),\n             aes(x = mean_reading, \n                 y = jobstatus), \n              alpha=0.4, \n             shape = 23, size = 3, colour = \"#f27279\", fill = \"#f27279\", stroke = .5) +\n  scale_color_manual(name=\"Parent\",\n                        values = c(\"Father\" = \"#73b2c4\", \n                               \"Mother\" = \"#f27279\")) +\n  scale_fill_manual(values = c(\"Father\" = \"#73b2c4\", \n                               \"Mother\" = \"#f27279\")) +\n  labs(\n    x = \"Reading\", \n  ) +\n  scale_y_discrete(expand = c(0, 0.1))+\n  guides(color=\"none\") +\n  theme(\n    legend.direction = \"horizontal\",\n    legend.position = \"bottom\",\n    plot.title = element_text(size =12, face = \"bold\"),\n    plot.subtitle = element_text(size = rel(0.8)),\n    plot.caption = element_text(size = rel(0.8)),\n    axis.text.x = element_text(size = rel(0.9)),\n    axis.title.y = element_blank(),\n    axis.text.y = element_blank(),\n    plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\") ) +\n  annotate(geom = \"text\", x = 0.08, y = 1.4, label = \"Density plots almost\\noverlap completely.\", hjust = \"left\", size= 2)  \n  \np_parentsjs_s <-\nggplot(jobstatus_long, \n       aes(x = Avg_Sci, y = jobstatus,\n           fill = parent,\n           color=parent)) +\n  geom_density_ridges(\n    calc_ecdf = TRUE, \n  # Reduce space between between education levels \n    scale = 0.8,\n    alpha= 0.3,\n  rel_min_height = 0.01,\n  position = position_nudge(y=0.11)\n  ) +\n  # point for father's mean\n  geom_point(data = subset(means_parentsjobstat, parent==\"Father\"),\n             aes(x = mean_sci, \n                 y = jobstatus), \n              alpha=0.4,\n             shape = 21, size = 3, colour = \"#73b2c4\", fill = \"#73b2c4\") +\n  # point for mother's \n  geom_point(data = subset(means_parentsjobstat, parent==\"Mother\"),\n             aes(x = mean_sci, \n                 y = jobstatus), \n              alpha=0.4,\n             shape = 23, size = 3, colour = \"#f27279\", fill = \"#f27279\", stroke = .5) +\n  scale_color_manual(name=\"Parent\",\n                        values = c(\"Father\" = \"#73b2c4\", \n                               \"Mother\" = \"#f27279\")) +\n  scale_fill_manual(values = c(\"Father\" = \"#73b2c4\", \n                               \"Mother\" = \"#f27279\")) +\n  labs(\n    x = \"Science\", \n  ) +\n  scale_y_discrete(expand = c(0, 0.1))+\n  guides(color=\"none\") +\n  theme(\n    legend.direction = \"horizontal\",\n    legend.position = \"bottom\",\n    plot.title = element_text(size =12, face = \"bold\"),\n    plot.subtitle = element_text(size = rel(0.8)),\n    plot.caption = element_text(size = rel(0.8)),\n    axis.text.x = element_text(size = rel(0.9)),\n    axis.title.y = element_blank(),\n    axis.text.y = element_blank(),\n    plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\") ) +\n  annotate(\n    geom = \"curve\", x = 280, y = 2.75\n    , xend = 470, yend = 2.80, \n    curvature = -.3, arrow = arrow(length = unit(2, \"mm\"))\n  ) +\n  annotate(geom = \"text\", x = 0.08, y = 2.6, label = \"Scores more\\nleft-skewed for\\nstudents with\\nunemployed\\nfathers.\", hjust = \"left\", size= 2)  \n  \n\n(p_parentsjs_m + p_parentsjs_r + p_parentsjs_s) +\n  plot_layout(guides = \"collect\") +\n  plot_annotation(title = \"Higher scores with employed parents.\",\n  subtitle=\"Students with unemployed <span style='color: #73b2c4;'>fathers</span> had better scores than those with unemployed <span style='color: #f27279;'>mothers</span>.\",\n                  theme=theme(plot.title = element_markdown(hjust = 0),\n                              plot.subtitle = element_markdown(hjust = 0),\n                  plot.background = element_rect(fill=\"#f5f5f5\", colour = \"#f5f5f5\"),\n                  panel.border = element_blank()))+\n  plot_layout(widths=c(1,1,1))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\n::: {.nursebox .nurse data-latex=\"nurse\"}\n**Insights**\n\n-   Mean scores are observed to be higher for students whose parents are employed as opposed to those with unemployed parents. In instances where both parents are employed, the corresponding density plots converge almost completely, suggesting that the employment status of either parent has a minimal effect on subject scores. This indicates a potentially equivalent influence of each parent's employment on academic outcomes.\n\n-   When focusing on the impact of unemployment, we notice a marked difference, especially in the case of the father's unemployment. The density plots tend to shift towards the right, implying an improvement in scores. This skew is further substantiated by the position of the blue geom points, which represent the average scores associated with father's unemployment. These points are now situated to the right of the pink points, which indicate the average scores when mothers are unemployed. This pattern might suggest that a father's unemployment could have a more significant positive correlation with student scores compared to a mother's unemployment.\n:::\n\n### 6.4.3 Nativity / Immigration Status\n\nJittered strip chart, using `geom_jitter`, is used in the visualisation of individual data points, allowing for a clearer observation of the variation and range differences between groups. The `geom_jitter` function adds a small amount of random variation to the position of each point, which helps to prevent overplotting where points would otherwise overlap completely.\n\nIn the accompanying code, the parameter `alpha = 0.2` is adjusted to control the transparency of the dots. An alpha value closer to 0 increases the transparency of the dots, making them more see-through, while a value closer to 1 would render them fully opaque. By setting the alpha to a lower value, we can clearly see the areas with a higher concentration of overlapping dots, which will naturally appear darker.\n\nFurthermore, `stat_summary()` is used to aggregate and display the median value for each group within the data. By specifying a contrasting color for these summary points, they are made to stand out against the jittered points, ensuring that these key statistical indicators draw immediate attention. This can be compared against the plotted mean line which shows the average score of each subject.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nimmig_m <-\nggplot(stu_SG_more, aes(x = Immigration_Status, \n                        y = Avg_Math, \n                        color = Immigration_Status)) +\n    coord_flip() +\n  geom_jitter(size = 2, \n              alpha = 0.2, \n              width = 0.2) +\n  stat_summary(color=\"#595DE5\",\n               fun = \"median\", \n               geom = \"point\", \n               size = 3, \n               alpha = 0.8)  +\n  scale_y_continuous(\n    breaks = scales::pretty_breaks(n = 5)\n  ) +  \n  geom_hline(aes(yintercept = mean_math), \n             linewidth=0.6,\n             linetype=\"dashed\",\n             color = \"red\")+\n  annotate(\n      \"text\", \n      x = 3.5, \n      y = 690,\n      label = paste(\"Mean =\\n\", round(mean_math, 3)),\n      color = \"red\",\n      size = 3\n    ) +\n  theme_minimal() +\n  theme(legend.position = \"none\",\n          plot.title = element_markdown(size = 12, face = \"bold\"),\n          plot.subtitle = element_text(size = rel(0.8)),\n          plot.caption = element_text(size = rel(0.8)),\n          axis.text.y = element_text(size = rel(0.9)),\n          axis.text.x = element_text(size = rel(0.9)),\n          axis.title.x = element_text(size = rel(0.8)),\n          axis.title.y = element_text(size = rel(0.8)),\n          axis.ticks.y = element_blank(),\n          panel.grid = element_blank(),\n          axis.line.x=element_line(),\n          plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n          ) +\n  guides(color = \"none\", fill = \"none\") + \n  scale_color_manual(values=c(\"#f27279\", \"#f7af7a\", \"#73b2c4\")) +\n  labs(x = NULL , y = \"Math\", title = \"\")\n\nimmig_r <-\nggplot(stu_SG_more, aes(x = Immigration_Status, \n                        y = Avg_Reading, \n                        color = Immigration_Status)) +\n    coord_flip() +\n  geom_jitter(size = 2, \n              alpha = 0.2, \n              width = 0.2) +\n  stat_summary(color=\"#595DE5\",\n               fun = \"median\", \n               geom = \"point\", \n               size = 3, \n               alpha = 0.8)  +\n  scale_y_continuous(\n    breaks = scales::pretty_breaks(n = 5)\n  ) +  \n  geom_hline(aes(yintercept = mean_reading), \n             linewidth=0.6,\n             linetype=\"dashed\",\n             color = \"red\")+\n  annotate(\n      \"text\", \n      x = 3.5, \n      y = 690,\n      label = paste(\"Mean =\\n\", round(mean_reading, 3)),\n      color = \"red\",\n      size = 3\n    ) +\n  theme_minimal() +\n  theme(legend.position = \"none\",\n          plot.title = element_markdown(size = 12, face = \"bold\"),\n          plot.subtitle = element_text(size = rel(0.8)),\n          plot.caption = element_text(size = rel(0.8)),\n          axis.text.y = element_blank(),\n          axis.text.x = element_text(size = rel(0.9)),\n          axis.title.x = element_text(size = rel(0.8)),\n          axis.title.y = element_text(size = rel(0.8)),\n          axis.ticks.y = element_blank(),\n          panel.grid = element_blank(),\n          axis.line.x=element_line(),\n          plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n          ) +\n  guides(color = \"none\", fill = \"none\") + \n  scale_color_manual(values=c(\"#f27279\", \"#f7af7a\", \"#73b2c4\")) +\n  labs(x = NULL , y = \"Reading\", title = \"\")\n\nimmig_s <-\nggplot(stu_SG_more, aes(x = Immigration_Status, \n                        y = Avg_Sci, \n                        color = Immigration_Status)) +\n    coord_flip() +\n  geom_jitter(size = 2, \n              alpha = 0.2, \n              width = 0.2) +\n  stat_summary(color=\"#595DE5\",\n               fun = \"median\", \n               geom = \"point\", \n               size = 3, \n               alpha = 0.8)  +\n  scale_y_continuous(\n    breaks = scales::pretty_breaks(n = 5)\n  ) +  \n  geom_hline(aes(yintercept = mean_sci), \n             linewidth=0.6,\n             linetype=\"dashed\",\n             color = \"red\")+\n  annotate(\n      \"text\", \n      x = 3.5, \n      y = 690,\n      label = paste(\"Mean =\\n\", round(mean_sci, 3)),\n      color = \"red\",\n      size = 3\n    ) +\n  theme_minimal() +\n  theme(legend.position = \"none\",\n          plot.title = element_markdown(size = 12, face = \"bold\"),\n          plot.subtitle = element_text(size = rel(0.8)),\n          plot.caption = element_text(size = rel(0.8)),\n          axis.text.y = element_blank(),\n          axis.text.x = element_text(size = rel(0.9)),\n          axis.title.x = element_text(size = rel(0.8)),\n          axis.title.y = element_text(size = rel(0.8)),\n          axis.ticks.y = element_blank(),\n          panel.grid = element_blank(),\n          axis.line.x=element_line(),\n          plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\")\n          ) +\n  guides(color = \"none\", fill = \"none\") + \n  scale_color_manual(values=c(\"#f27279\", \"#f7af7a\", \"#73b2c4\")) +\n  labs(x = NULL , y = \"Science\", title = \"\")\n\n(immig_m | immig_r | immig_s) +\n    plot_annotation(title=\"Higher scores from <span style='color: #f7af7a;'>Second-gen immigrants</span> across all subjects.\", \n                  theme=theme(plot.title = element_markdown(hjust = 0),\n                              plot.subtitle = element_markdown(hjust = 0),\n                  plot.background = element_rect(fill=\"#f5f5f5\", colour = \"#f5f5f5\"),\n                  panel.border = element_blank()))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\n::: {.nursebox .nurse data-latex=\"nurse\"}\n**Insights**\n\n-   Plots of raw data helps with \"sanity checking\" and identify things like missing data or outliers, while plots of summary statistics helps visual estimation against other groups. This dual approach ensures a comprehensive understanding of the data set, allowing for both detailed individual data point analysis and aggregate group comparisons.\n\n-   The results derived from the jittered plots indicate that second-generation immigrants generally outperform their peers in all subjects. This observation suggests that there might be underlying factors or conditions conducive to the academic success of this demographic group.\n\n-   The natives exhibit the widest range of scores, contributing to a lower median. This wider spread signifies greater variability in performance among native students.\n:::\n\n## 6.5 Comparing home access to educational resources\n\nThe raincloud plot combines an illustration of data distribution (the 'cloud'), with jittered raw data (the 'rain'). This can be further supplemented by adding boxplots or other standard measures of central tendency and error. Thus, raincloud plots offer the reader maximum utility and flexibility, ensuring that nothing is 'hidden away' and that the reader has all informaiton needed to assess the data, its distribution, and the appropriateness of any statistical tests in a visually appealing format.\n\nIn the code chunk below, we use [`stat_halfeye`](https://mjskay.github.io/ggdist/reference/stat_halfeye.html) to create a halved distribution, `geom_boxplot` for the boxplot, and `geom_point` for the jitters. An `ifelse()` condition is added to the stat_halfeye aesthetic to flip the density plot horizontally when the result is 'No'. This allows closer side-by-side comparison of the boxplots for each pair of answer to the survey question.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Math\nrcp_com_m <- \n  ggplot(stu_SG_more, aes(x = Have_Comp, \n                          y = Avg_Math, \n                          fill = Have_Comp)) +\n  \n  stat_halfeye(aes(fill = Have_Comp,\n                         justification = ifelse(Have_Comp == \"No\", 1.2, 0),\n                          side = ifelse(Have_Comp == \"No\", \"left\", \"right\")),\n                   position = position_nudge(x = .1, y = 0), \n                   adjust = 1.2, \n                   .width=0,\n                   trim = FALSE, \n                   alpha = .5, \n                   point_colour = NA,\n                   orientation = )+\n  \n  geom_point(aes(x = Have_Comp, \n                 y = Avg_Math, \n                 colour = Have_Comp),\n             position = position_jitter(width = .05), \n             size = .25, \n             shape = 20)+\n  \n  geom_boxplot(aes(x = Have_Comp, \n                   y = Avg_Math, \n                   fill = Have_Comp),\n               outlier.shape = NA, \n               alpha = .5, \n               width = .1, \n               colour = \"black\")+\n  scale_color_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  scale_fill_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  labs(\n    x = \"Computer\", \n  ) +\n  theme_minimal() +  \n  ylim(100, 920)+\n  theme(\n    legend.direction = \"horizontal\",\n    legend.position=\"none\",\n    plot.title = element_text(size =12, face = \"bold\"),\n    plot.subtitle = element_text(size = rel(0.8)),\n    plot.caption = element_text(size = rel(0.8)),\n    axis.text.x = element_text(size = rel(0.9)),\n    axis.title.x = element_text(size = rel(0.9)),\n    axis.title.y = element_blank(),\n    axis.text.y = element_text(size = rel(0.8)),\n    plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\") )   +\n  geom_hline(aes(yintercept=mean_math),\n               color=\"#595DE5\", linewidth=0.7, linetype=\"dashed\") +\n  annotate(\n      \"text\", \n      x = 1.5, \n      y = mean_math +80,\n      label = paste(\"Mean\\nScore =\\n\", mean_math),\n      color = \"#595DE5\",\n      size = 2.5\n    )\n\n\nrcp_sw_m <- \n  ggplot(stu_SG_more, aes(x = Have_EduSW, \n                          y = Avg_Math, \n                          fill = Have_EduSW)) +\n  \n  stat_halfeye(aes(fill = Have_EduSW,\n                         justification = ifelse(Have_EduSW == \"No\", 1.2, 0),\n                          side = ifelse(Have_EduSW == \"No\", \"left\", \"right\")),\n                   position = position_nudge(x = .1, y = 0), \n                   adjust = 1.2, \n                   .width=0,\n                   trim = FALSE, \n                   alpha = .5, \n                   point_colour = NA,\n                   orientation = )+\n  \n  geom_point(aes(x = Have_EduSW, \n                 y = Avg_Math, \n                 colour = Have_EduSW),\n             position = position_jitter(width = .05), \n             size = .25, \n             shape = 20)+\n  \n  geom_boxplot(aes(x = Have_EduSW, \n                   y = Avg_Math, \n                   fill = Have_EduSW),\n               outlier.shape = NA, \n               alpha = .5, \n               width = .1, \n               colour = \"black\")+\n  scale_color_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  scale_fill_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  labs(\n    x = \"Educational Software\", \n  ) +\n  ylim(100, 920)+\n    theme_minimal() +  \n  theme(\n    legend.direction = \"horizontal\",\n    legend.position=\"none\",\n    plot.title = element_text(size =12, face = \"bold\"),\n    plot.subtitle = element_text(size = rel(0.8)),\n    plot.caption = element_text(size = rel(0.8)),\n    axis.text.x = element_text(size = rel(0.9)),\n    axis.title.y = element_blank(),\n    axis.title.x = element_text(size = rel(0.9)),\n    axis.text.y = element_blank(),\n    plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\") )   +\n  geom_hline(aes(yintercept=mean_math),\n               color=\"#595DE5\", linewidth=0.7, linetype=\"dashed\")\n\nrcp_int_m <- \n  ggplot(stu_SG_more, aes(x = Have_Internet, \n                          y = Avg_Math, \n                          fill = Have_Internet)) +\n  \n  stat_halfeye(aes(fill = Have_Internet,\n                         justification = ifelse(Have_Internet == \"No\", 1.2, 0),\n                          side = ifelse(Have_Internet == \"No\", \"left\", \"right\")),\n                   position = position_nudge(x = .1, y = 0), \n                   adjust = 1.2, \n                   .width=0,\n                   trim = FALSE, \n                   alpha = .5, \n                   point_colour = NA,\n                   orientation = )+\n  \n  geom_point(aes(x = Have_Internet, \n                 y = Avg_Math, \n                 colour = Have_Internet),\n             position = position_jitter(width = .05), \n             size = .25, \n             shape = 20)+\n  \n  geom_boxplot(aes(x = Have_Internet, \n                   y = Avg_Math, \n                   fill = Have_Internet),\n               outlier.shape = NA, \n               alpha = .5, \n               width = .1, \n               colour = \"black\")+\n  scale_color_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  scale_fill_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  labs(\n    x = \"Internet\", \n  ) +\n  ylim(100, 920)+\n    theme_minimal() +  \n  theme(\n    legend.direction = \"horizontal\",\n    legend.position=\"none\",\n    plot.title = element_text(size =12, face = \"bold\"),\n    plot.subtitle = element_text(size = rel(0.8)),\n    plot.caption = element_text(size = rel(0.8)),\n    axis.text.x = element_text(size = rel(0.9)),\n    axis.title.x = element_text(size = rel(0.9)),\n    axis.title.y = element_blank(),\n        axis.text.y = element_blank(),\n    plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\") )  +\n  geom_hline(aes(yintercept=mean_math),\n               color=\"#595DE5\", linewidth=0.7, linetype=\"dashed\")  \n\nrcp_m <-\nrcp_com_m + rcp_sw_m + rcp_int_m +\n  plot_layout(widths=c(1,1,1)) +\n  plot_annotation(title=\"Math\", \n                  theme=theme(plot.title = element_text(hjust = 0),\n                  plot.background = element_rect(fill=\"#f5f5f5\", colour = \"#f5f5f5\"),\n                  panel.border = element_blank()))\n\nrcp_m\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Reading\nrcp_com_r <- \n  ggplot(stu_SG_more, aes(x = Have_Comp, \n                          y = Avg_Reading, \n                          fill = Have_Comp)) +\n  \n  stat_halfeye(aes(fill = Have_Comp,\n                         justification = ifelse(Have_Comp == \"No\", 1.2, 0),\n                          side = ifelse(Have_Comp == \"No\", \"left\", \"right\")),\n                   position = position_nudge(x = .1, y = 0), \n                   adjust = 1.2, \n                   .width=0,\n                   trim = FALSE, \n                   alpha = .5, \n                   point_colour = NA,\n                   orientation = )+\n  \n  geom_point(aes(x = Have_Comp, \n                 y = Avg_Reading, \n                 colour = Have_Comp),\n             position = position_jitter(width = .05), \n             size = .25, \n             shape = 20)+\n  \n  geom_boxplot(aes(x = Have_Comp, \n                   y = Avg_Reading, \n                   fill = Have_Comp),\n               outlier.shape = NA, \n               alpha = .5, \n               width = .1, \n               colour = \"black\")+\n  scale_color_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  scale_fill_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  labs(\n    x = \"Computer\", \n  ) +\n  ylim(100, 920)+\n    theme_minimal() +  \n  theme(\n    legend.direction = \"horizontal\",\n    legend.position=\"none\",\n    plot.title = element_text(size =12, face = \"bold\"),\n    plot.subtitle = element_text(size = rel(0.8)),\n    plot.caption = element_text(size = rel(0.8)),\n    axis.text.x = element_text(size = rel(0.9)),\n    axis.title.x = element_text(size = rel(0.9)),\n    axis.title.y = element_blank(),\n    axis.text.y = element_text(size = rel(0.8)),\n    plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\") )   +\n  geom_hline(aes(yintercept=mean_reading),\n               color=\"#595DE5\", linewidth=0.7, linetype=\"dashed\") +\n  annotate(\n      \"text\", \n      x = 1.5, \n      y = mean_math +80,\n      label = paste(\"Mean\\nScore =\\n\", mean_reading),\n      color = \"#595DE5\",\n      size = 2.5\n    )  \n  \n\nrcp_sw_r <- \n  ggplot(stu_SG_more, aes(x = Have_EduSW, \n                          y = Avg_Reading, \n                          fill = Have_EduSW)) +\n  \n  stat_halfeye(aes(fill = Have_EduSW,\n                         justification = ifelse(Have_EduSW == \"No\", 1.2, 0),\n                          side = ifelse(Have_EduSW == \"No\", \"left\", \"right\")),\n                   position = position_nudge(x = .1, y = 0), \n                   adjust = 1.2, \n                   .width=0,\n                   trim = FALSE, \n                   alpha = .5, \n                   point_colour = NA,\n                   orientation = )+\n  \n  geom_point(aes(x = Have_EduSW, \n                 y = Avg_Reading, \n                 colour = Have_EduSW),\n             position = position_jitter(width = .05), \n             size = .25, \n             shape = 20)+\n  \n  geom_boxplot(aes(x = Have_EduSW, \n                   y = Avg_Reading, \n                   fill = Have_EduSW),\n               outlier.shape = NA, \n               alpha = .5, \n               width = .1, \n               colour = \"black\")+\n  scale_color_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  scale_fill_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  labs(\n    x = \"Educational Software\", \n  ) +\n  ylim(100, 920)+\n    theme_minimal() +  \n  theme(\n    legend.direction = \"horizontal\",\n    legend.position=\"none\",\n    plot.title = element_text(size =12, face = \"bold\"),\n    plot.subtitle = element_text(size = rel(0.8)),\n    plot.caption = element_text(size = rel(0.8)),\n    axis.text.x = element_text(size = rel(0.9)),\n    axis.title.x = element_text(size = rel(0.9)),\n    axis.title.y = element_blank(),\n        axis.text.y = element_blank(),\n    plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\") )  +\n  geom_hline(aes(yintercept=mean_reading),\n               color=\"#595DE5\", linewidth=0.7, linetype=\"dashed\")  \n  \n\nrcp_int_r <- \n  ggplot(stu_SG_more, aes(x = Have_Internet, \n                          y = Avg_Reading, \n                          fill = Have_Internet)) +\n  \n  stat_halfeye(aes(fill = Have_Internet,\n                         justification = ifelse(Have_Internet == \"No\", 1.2, 0),\n                          side = ifelse(Have_Internet == \"No\", \"left\", \"right\")),\n                   position = position_nudge(x = .1, y = 0), \n                   adjust = 1.2, \n                   .width=0,\n                   trim = FALSE, \n                   alpha = .5, \n                   point_colour = NA,\n                   orientation = )+\n  \n  geom_point(aes(x = Have_Internet, \n                 y = Avg_Reading, \n                 colour = Have_Internet),\n             position = position_jitter(width = .05), \n             size = .25, \n             shape = 20)+\n  \n  geom_boxplot(aes(x = Have_Internet, \n                   y = Avg_Reading, \n                   fill = Have_Internet),\n               outlier.shape = NA, \n               alpha = .5, \n               width = .1, \n               colour = \"black\")+\n  scale_color_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  scale_fill_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  labs(\n    x = \"Internet\", \n  ) +\n  ylim(100, 920)+\n    theme_minimal() +  \n  theme(\n    legend.direction = \"horizontal\",\n    legend.position=\"none\",\n    plot.title = element_text(size =12, face = \"bold\"),\n    plot.subtitle = element_text(size = rel(0.8)),\n    plot.caption = element_text(size = rel(0.8)),\n    axis.text.x = element_text(size = rel(0.9)),\n    axis.title.x = element_text(size = rel(0.9)),\n    axis.title.y = element_blank(),\n        axis.text.y = element_blank(),\n    plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\") )   +\n  annotate(\n    geom = \"curve\", x = 0.3, y = 230, xend = 0.7, yend = 300, \n    curvature = -.3, arrow = arrow(length = unit(2, \"mm\"))\n  ) +\n  annotate(geom = \"text\", x =0.02, y = 185, label = \"Highly\\nleft-skewed\", hjust = \"left\", size= 3)  +\n  geom_hline(aes(yintercept=mean_reading),\n               color=\"#595DE5\", linewidth=0.7, linetype=\"dashed\")  \n    \n\n\nrcp_r <-\nrcp_com_r + rcp_sw_r + rcp_int_r +\n  plot_layout(widths=c(1,1,1)) +\n  plot_annotation(title=\"Reading\", \n                  theme=theme(plot.title = element_text(hjust = 0),\n                  plot.background = element_rect(fill=\"#f5f5f5\", colour = \"#f5f5f5\"),\n                  panel.border = element_blank()))\n\nrcp_r\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Reading\nrcp_com_s <- \n  ggplot(stu_SG_more, aes(x = Have_Comp, \n                          y = Avg_Sci, \n                          fill = Have_Comp)) +\n  \n  stat_halfeye(aes(fill = Have_Comp,\n                         justification = ifelse(Have_Comp == \"No\", 1.2, 0),\n                          side = ifelse(Have_Comp == \"No\", \"left\", \"right\")),\n                   position = position_nudge(x = .1, y = 0), \n                   adjust = 1.2, \n                   .width=0,\n                   trim = FALSE, \n                   alpha = .5, \n                   point_colour = NA,\n                   orientation = )+\n  \n  geom_point(aes(x = Have_Comp, \n                 y = Avg_Sci, \n                 colour = Have_Comp),\n             position = position_jitter(width = .05), \n             size = .28, \n             shape = 20)+\n  \n  geom_boxplot(aes(x = Have_Comp, \n                   y = Avg_Sci, \n                   fill = Have_Comp),\n               outlier.shape = NA, \n               alpha = .5, \n               width = .1, \n               colour = \"black\")+\n  scale_color_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  scale_fill_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  labs(\n    x = \"Computer\", \n  ) +\n  ylim(100, 920)+\n    theme_minimal() +  \n  theme(\n    legend.direction = \"horizontal\",\n    legend.position=\"none\",\n    plot.title = element_text(size =12, face = \"bold\"),\n    plot.subtitle = element_text(size = rel(0.8)),\n    plot.caption = element_text(size = rel(0.8)),\n    axis.text.x = element_text(size = rel(0.9)),\n    axis.title.x = element_text(size = rel(0.9)),\n    axis.title.y = element_blank(),\n    axis.text.y = element_text(size = rel(0.8)),\n    plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\") ) +\n  geom_hline(aes(yintercept=mean_sci),\n               color=\"#595DE5\", linewidth=0.7, linetype=\"dashed\") +\n  annotate(\n      \"text\", \n      x = 1.5, \n      y = mean_math +80,\n      label = paste(\"Mean\\nScore =\\n\", mean_sci),\n      color = \"#595DE5\",\n      size = 2.5\n    )  \n  \n\nrcp_sw_s <- \n  ggplot(stu_SG_more, aes(x = Have_EduSW, \n                          y = Avg_Sci, \n                          fill = Have_EduSW)) +\n  \n  stat_halfeye(aes(fill = Have_EduSW,\n                         justification = ifelse(Have_EduSW == \"No\", 1.2, 0),\n                          side = ifelse(Have_EduSW == \"No\", \"left\", \"right\")),\n                   position = position_nudge(x = .1, y = 0), \n                   adjust = 1.2, \n                   .width=0,\n                   trim = FALSE, \n                   alpha = .5, \n                   point_colour = NA,\n                   orientation = )+\n  \n  geom_point(aes(x = Have_EduSW, \n                 y = Avg_Sci, \n                 colour = Have_EduSW),\n             position = position_jitter(width = .05), \n             size = .28, \n             shape = 20)+\n  \n  geom_boxplot(aes(x = Have_EduSW, \n                   y = Avg_Sci, \n                   fill = Have_EduSW),\n               outlier.shape = NA, \n               alpha = .5, \n               width = .1, \n               colour = \"black\")+\n  scale_color_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  scale_fill_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  labs(\n    x = \"Educational Software\", \n  ) +\n  ylim(100, 920)+\n    theme_minimal() +  \n  theme(\n    legend.direction = \"horizontal\",\n    legend.position=\"none\",\n    plot.title = element_text(size =12, face = \"bold\"),\n    plot.subtitle = element_text(size = rel(0.8)),\n    plot.caption = element_text(size = rel(0.8)),\n    axis.text.x = element_text(size = rel(0.9)),\n    axis.title.x = element_text(size = rel(0.9)),\n    axis.title.y = element_blank(),\n        axis.text.y = element_blank(),\n    plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\") )  + \n  geom_hline(aes(yintercept=mean_sci),\n               color=\"#595DE5\", linewidth=0.7, linetype=\"dashed\")   \n\nrcp_int_s <- \n  ggplot(stu_SG_more, aes(x = Have_Internet, \n                          y = Avg_Sci, \n                          fill = Have_Internet)) +\n  \n  stat_halfeye(aes(fill = Have_Internet,\n                         justification = ifelse(Have_Internet == \"No\", 1.2, 0),\n                          side = ifelse(Have_Internet == \"No\", \"left\", \"right\")),\n                   position = position_nudge(x = .1, y = 0), \n                   adjust = 1.2, \n                   .width=0,\n                   trim = FALSE, \n                   alpha = .5, \n                   point_colour = NA,\n                   orientation = )+\n  \n  geom_point(aes(x = Have_Internet, \n                 y = Avg_Sci, \n                 colour = Have_Internet),\n             position = position_jitter(width = .05), \n             size = .28, \n             shape = 20)+\n  \n  geom_boxplot(aes(x = Have_Internet, \n                   y = Avg_Sci, \n                   fill = Have_Internet),\n               outlier.shape = NA, \n               alpha = .5, \n               width = .1, \n               colour = \"black\")+\n  scale_color_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  scale_fill_manual(values = c(\"No\" = \"#73b2c4\", \n                               \"Yes\" = \"#f27279\")) +\n  labs(\n    x = \"Internet\", \n  ) +\n  ylim(100, 920)+\n    theme_minimal() +  \n  theme(\n    legend.direction = \"horizontal\",\n    legend.position=\"none\",\n    plot.title = element_text(size =12, face = \"bold\"),\n    plot.subtitle = element_text(size = rel(0.8)),\n    plot.caption = element_text(size = rel(0.8)),\n    axis.text.x = element_text(size = rel(0.9)),\n    axis.title.x = element_text(size = rel(0.9)),\n    axis.title.y = element_blank(),\n        axis.text.y = element_blank(),\n    plot.background=element_rect(fill=\"#f5f5f5\",colour=\"#f5f5f5\") ) +  \n  geom_hline(aes(yintercept=mean_sci),\n               color=\"#595DE5\", linewidth=0.7, linetype=\"dashed\") \n\nrcp_s <-\nrcp_com_s + rcp_sw_s + rcp_int_s +\n  plot_layout(widths=c(1,1,1)) +\n  plot_annotation(title=\"Science\", \n                  theme=theme(plot.title = element_text(hjust = 0),\n                  plot.background = element_rect(fill=\"#f5f5f5\", colour = \"#f5f5f5\"),\n                  panel.border = element_blank()))\n\nrcp_s\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\n::: {.nursebox .nurse data-latex=\"nurse\"}\n**Insights**\n\n-   Across all 3 subjects, students with limited home access to key study resources, such as computers, educational software, and internet, tend to have lower scores. This pattern is particularly pronounced in cases of internet inaccessibility, leading to noticeably left-skewed score distributions, especially in Reading. The lack of internet access appears to significantly hinder students' ability to access information and educational materials, which is reflected in their academic performance.\n-   Interestingly, access to educational software seems to have a relatively minor impact on overall scores compared to other resources. This observation suggests that while educational software can be a useful tool, its absence does not disadvantage students as severely as the lack of more fundamental resources like internet access. This insight could guide educational policies and resource allocation, emphasizing the critical importance of internet access for student learning and achievement.\n-   These observations highlight the crucial role of basic educational resources in student performance and the varying degrees of impact different resources can have. This understanding is vital for developing targeted strategies to bridge educational gaps and enhance learning outcomes.\n-   However, recall our sample size for students without access to educational tools are low (see Section 5.3), which might reduce the accuracy of our finding.\n:::\n\n# 7 Summary\n\nOur analysis of the Singapore students' performance in mathematics, reading, and science, and the relationship between these performances with schools, gender and socioeconomic status of the students yielded several insights. Overall, our analysis revealed uneven distributions of scores with different genders, time spent on homework, type of schools, home access to key resources, and socio-economic status.\n\nKey Findings:\n\n-   There is an improvement in scores with increased time spent on homework, although the benefits diminish beyond a certain point.\n-   Male students tend to achieve slightly higher scores than females.\n-   The type of school and student-teacher ratios did not show consistent trends in relation to student performance.\n-   A lower educational attainment by fathers seems to slightly inversely affect student outcomes.\n-   Father's unemployment shows a more significant positive correlation with student scores compared to mother's unemployment.\n-   Second-generation immigrants are generally outperforming their peers across all subjects.\n-   Student performance is noticeably influenced by home access to basic educational resources, with varying impacts depending on the type of resource.\n\nRecommendations for future research:\n\n-   **Confirmatory data analysis:** Future studies should incorporate statistical tests to validate the findings from this exploratory data analysis and establish more definitive correlations and causation.\n-   **Exploring Additional Variables**: A more exhaustive analysis that includes a wider range of variables could yield deeper insights into student performance. Investigating psychological factors such as student motivation, stress levels, and mental health is crucial to understand their impact on academic outcomes. Additionally, the role of teacher qualifications, teaching methods, and classroom environments warrants further exploration to assess their influence on student achievement.\n-   **Longitudinal Studies:** Conducting longitudinal studies to track changes in student performance over time can reveal trends and causal effects that cross-sectional studies might miss.\n-   **Economic Factors**: While this study utilised home access to educational resources as a proxy for students' economic backgrounds, incorporating direct measures such as household income could offer a more accurate assessment of economic influence.\n\nBy addressing these areas, future research can provide a more comprehensive understanding of the various factors that contribute to student performance, thereby aiding in the development of targeted educational strategies and policies.\n\n# 8 References and inspiration\n\nKam, Tin Seong. (2023). Visualising Distribution. *R for Visual Analytics.* <https://r4va.netlify.app/chap09>\n\nScherer, Cedric. (2019). A ggplot2 Tutorial for Beautiful Plotting in R. *Cedric Scherer.* [https://www.cedricscherer.com/2019/08/05/a-ggplot2-tutorial-for-beautiful-plotting-in-r/](https://www.cedricscherer.com/2019/08/05/a-ggplot2-tutorial-for-beautiful-plotting-in-r/https://www.cedricscherer.com/2019/08/05/a-ggplot2-tutorial-for-beautiful-plotting-in-r/)\n\nShuga, Aubrey. (2021). Exploring the raincloudplots Package. *Aubrey Shuga.* <https://aubreyshuga.netlify.app/post/exploring-the-raincloudplots-package-2/>\n\nWong, Kenneth. (2020). 3D pedestrian network dataset of Hong Kong - A Quick Look. *Urban Data Palette.* <https://urbandatapalette.com/post/2020-12-3dpn-quick-look/>\n",
    "supporting": [
      "Take-home_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}