---
title: "Take-home Exercise 4: Prototyping Modules for Shiny Application"
date: "?? Feb 2024"
date-modified: "last-modified"
editor: visual
toc-depth: 4
execute:
  freeze: true #never re-render during project render
  echo: true #if false, displays charts without codes
  eval: true #if false, displays codes without charts
  warning: false #dont display if there are any warnings
format: 
  html:
    code-fold: false
    code-overflow: scroll
    code-summary: "Show the code"
    code-line-numbers: false
---

Load in the csv file following minor data cleaning and wrangling documented [here]().

```{r}
stu <- read_csv("data/stu_SG_rcd.csv")
stu_encode <- read_csv("data/stu_SG_encode.csv")
```

```{r}

```


```{mermaid}
%%| fig-width: 8
%%| echo: false

flowchart TD
    A[Building Explanatory Model] -->B[Feature Engineering]
    B -.->B1(Multicollinearity, Variable Selection, Variable Transformation, Principal Compponent Analysis)
    B-->C[Form: Regression Analysis]
    C -->D[Fit: Model Assessment]
    D -.->D1(R-Sq, Adjusted R2, RMSE)    
    D -->E[Fit: Model Comparison]
```

```{r}
pacman::p_load(tidyverse, ggplot2, lmtest, modelr, broom, vegan, recipes, DALEX, stargazer, corrplot)
```




# Collinearity



```{r}
par(bg = "#f5f5f5")

# Compute correlation matrix of student responses
stu.cor <- 
stu.sig = cor.mtest(stu, conf.level= .95) #<< 

corrplot(stu,
         method = "number",
         type = "lower",
         diag = FALSE,
         tl.col = "black",
         tl.srt = 90,
         p.mat = 0.05,
         sig.level = stu.sig$p, #<<
         tl.cex = 0.6,
         bg="#f5f5f5")
```





# Model Diagnostics

## Model Assumptions

## Checking Assumptions

# Model Building

# Model Assessment
